# Integration of variables and cases

In [1]:
import pandas as pd

In [15]:
cases = pd.read_csv('../../data/clean/casos_dengue.csv')
rr = pd.read_csv('../../data/clean/relative_risk.csv')
ndvi = pd.read_csv('../../data/clean/NDVI_int.csv')
lst = pd.read_csv('../../data/clean/LST_int.csv')
temp_max = pd.read_csv('../../data/clean/tmax_weekly.csv')
temp_min = pd.read_csv('../../data/clean/tmin_weekly.csv')
sst = pd.read_csv('../../data/clean/SST_int.csv')
# temp_min = pd.read_csv('../../data/clean/TNA_int.csv')
precip = pd.read_csv('../../data/clean/precip_weekly.csv')
urb = pd.read_csv('../../data/clean/urbanization.csv')

In [26]:
cases.head()

     casos week-canton
624      3  2020-1-101
625     11  2020-2-101
626     15  2020-3-101
627      7  2020-4-101
628      0  2020-5-101

In [29]:
no_total = ~cases['week-canton'].str.endswith("-0")
cases = cases[no_total]
no_total = ~cases['week-canton'].str.endswith("-1")
cases = cases[no_total]
no_total = ~cases['week-canton'].str.endswith("-2")
cases = cases[no_total]
no_total = ~cases['week-canton'].str.endswith("-3")
cases = cases[no_total]
no_total = ~cases['week-canton'].str.endswith("-4")
cases = cases[no_total]
no_total = ~cases['week-canton'].str.endswith("-5")
cases = cases[no_total]
no_total = ~cases['week-canton'].str.endswith("-6")
cases = cases[no_total]
no_total = ~cases['week-canton'].str.endswith("-7")
cases = cases[no_total]
no_total = ~cases['week-canton'].str.endswith("-99")
cases = cases[no_total]
no_total = ~cases['week-canton'].str.endswith("-98")
cases = cases[no_total]

In [27]:
no_total = ~cases['week-canton'].str.startswith("2020-53")
cases = cases[no_total]
no_total = ~cases['week-canton'].str.startswith("2021-53")
cases = cases[no_total]
no_total = ~cases['week-canton'].str.startswith("2022-53")
cases = cases[no_total]
no_total = ~cases['week-canton'].str.startswith("2023-53")
cases = cases[no_total]
no_total = ~cases['week-canton'].str.startswith("2024-53")
cases = cases[no_total]
no_total = ~cases['week-canton'].str.startswith("2025-53")
cases = cases[no_total]

In [6]:
rr.head()

         rr week-canton clasi_rr
0  0.258311  2020-1-101    Medio
1  0.930583  2020-2-101     Alto
2  1.356304  2020-3-101     Alto
3  0.657643  2020-4-101     Alto
4  0.000000  2020-5-101     Bajo

In [12]:
temp_max.drop(columns=["Unnamed: 0"], inplace=True)
temp_max.head()

    tmax_min   tmax_max  tmax_mean  tmax_median week_canton
0  33.185726  33.849937  33.578913    33.594887  2020-1-507
1  26.316240  27.293066  26.838383    26.761051  2020-1-112
2  25.749187  26.673803  26.204433    26.218884  2020-1-201
3  23.514788  24.153862  23.878840    23.849730  2020-1-110
4  21.239576  22.188282  21.588210    21.481771  2020-1-306

In [13]:
temp_min.drop(columns=["Unnamed: 0"], inplace=True)
temp_min.head()

    tmin_min   tmin_max  tmin_mean  tmin_median week_canton
0  24.307365  26.021297  24.814801    24.504314  2020-1-507
1  19.743813  20.537115  20.030698    19.975498  2020-1-112
2  17.587805  19.524090  18.199087    17.867570  2020-1-201
3  15.657812  16.869596  16.108704    15.963184  2020-1-110
4  13.576344  14.808821  14.152639    14.069752  2020-1-306

In [16]:
precip.drop(columns=["Unnamed: 0"], inplace=True)
precip.head()

,precip_total,precip_min,precip_max,precip_mean,precip_median,week_canton
0,3.039511,0.0,3.039511,0.607902,0.0,2020-1-507
1,46.348244,0.0,46.348244,9.269649,0.0,2020-1-112
2,5.230224,0.0,3.922668,1.046045,0.0,2020-1-201
3,11.819548,0.0,11.819548,2.363910,0.0,2020-1-110
4,27.190937,0.0,27.190937,5.438187,0.0,2020-1-306

In [17]:
ndvi.drop(columns=["Unnamed: 0"], inplace=True)
ndvi.head()

  week_canton    ndvi
0  2020-1-201  0.8913
1  2020-1-205  0.7437
2  2020-1-203  0.7113
3  2020-1-215  0.7439
4  2020-1-214  0.7885

In [18]:
lst.drop(columns=["Unnamed: 0"], inplace=True)
lst.head()

  week_canton     lst
0  2020-1-201   27.31
1  2020-1-205   29.77
2  2020-1-203   29.81
3  2020-1-215 -273.15
4  2020-1-214 -273.15

In [19]:
sst.drop(columns=["Unnamed: 0"], inplace=True)
sst.head()

  week_canton  nino12ssta  nino3ssta  nino4ssta
0  2020-1-101       -0.37       0.22       0.85
1  2020-1-102       -0.37       0.22       0.85
2  2020-1-103       -0.37       0.22       0.85
3  2020-1-104       -0.37       0.22       0.85
4  2020-1-105       -0.37       0.22       0.85

In [30]:
# Dimensions

print(f"""
      cases: {cases.shape}
      rr: {rr.shape}
      ndvi: {ndvi.shape}
      lst: {lst.shape}
      temp_max: {temp_max.shape}
      temp_min: {temp_min.shape}
      sst: {sst.shape}
      precip: {precip.shape}
      urb: {urb.shape}
      """)

      cases: (25584, 2)
      rr: (25584, 3)
      ndvi: (25584, 2)
      lst: (25584, 2)
      temp_max: (25010, 6)
      temp_min: (24682, 6)
      sst: (25584, 4)
      precip: (24682, 6)
      urb: (26076, 2)

# Join

In [48]:
print(f'Temp max shape: {temp_max.shape}, temp min shape: {temp_min.shape}')

Temp max shape: (20196, 5), temp min shape: (20196, 5)

In [49]:
temp = pd.merge(temp_max, temp_min, on='week-canton', how='outer')

In [50]:
temp.shape

(20196, 9)

In [51]:
temp.head()

,tmax_min,tmax_max,tmax_mean,tmax_median,week-canton,tmin_min,tmin_max,tmin_mean,tmin_median
0,26.380344,33.040943,29.733966,29.475617,2020-1-104,26.380344,33.040943,29.733966,29.475617
1,23.293335,29.497790,26.818812,27.263731,2020-1-105,23.293335,29.497790,26.818812,27.263731
2,25.323180,26.002405,25.682018,25.701244,2020-1-106,25.323180,26.002405,25.682018,25.701244
3,27.604164,28.397926,28.088817,28.176588,2020-1-107,27.604164,28.397926,28.088817,28.176588
4,25.913841,26.667221,26.356873,26.423215,2020-1-109,25.913841,26.667221,26.356873,26.423215

In [52]:
print(f'Temp shape: {temp.shape}, precip shape: {precip.shape}')

Temp shape: (20196, 9), precip shape: (19932, 6)

In [53]:
temp_precip = pd.merge(temp, precip, on='week-canton', how='right')

In [54]:
temp_precip.shape

(19932, 14)

In [55]:
temp_precip.head()

,tmax_min,tmax_max,tmax_mean,tmax_median,week-canton,tmin_min,tmin_max,tmin_mean,tmin_median,precip_total,precip_min,precip_max,precip_mean,precip_median
0,31.206179,34.216175,32.980368,33.278346,2020-1-507,31.206179,34.216175,32.980368,33.278346,16.483572,0.0,8.394386,0.686816,0.0
1,27.300568,31.489710,28.930743,28.016085,2020-1-112,27.300568,31.489710,28.930743,28.016085,77.464812,0.0,37.667015,6.455401,0.0
2,21.756056,29.411386,26.367157,27.010843,2020-1-201,21.756056,29.411386,26.367157,27.010843,56.828430,0.0,32.674007,3.551777,0.0
3,23.514788,24.153862,23.886117,23.937909,2020-1-110,23.514788,24.153862,23.886117,23.937909,11.819548,0.0,11.819548,2.954887,0.0
4,23.673475,24.585056,24.102187,24.075108,2020-1-306,23.673475,24.585056,24.102187,24.075108,27.596506,0.0,27.596506,6.899127,0.0

In [56]:
print(f'Cases shape: {cases.shape}, rr shape: {rr.shape}, urb shape: {urb.shape}')

Cases shape: (29256, 2), rr shape: (26076, 3), urb shape: (26076, 2)

In [57]:
rr.columns = ['relative_risk', 'week-canton', "classi_rr"]

In [58]:
cases_rr = pd.merge(cases, rr, on=['week-canton'], how='outer')

In [59]:
cases_rr.shape

(29256, 4)

In [60]:
cases_rr.head()

   casos week-canton  relative_risk classi_rr
0    168    2020-1-0            NaN       NaN
1     22    2020-1-1            NaN       NaN
2      3  2020-1-101       0.258220     Medio
3      0  2020-1-102       0.000000      Bajo
4      6  2020-1-103       0.751468      Alto

In [61]:
urb.head()

   URBANIZACION week-canton
0             1  2020-1-101
1             1  2020-1-102
2             1  2020-1-103
3             2  2020-1-104
4             2  2020-1-105

In [62]:
urb.columns = ['urb', 'week-canton']

In [63]:
demo = pd.merge(cases_rr, urb, on='week-canton', how='right')

In [64]:
demo.shape

(26076, 5)

In [65]:
demo.head()

   casos week-canton  relative_risk classi_rr  urb
0      3  2020-1-101       0.258220     Medio    1
1      0  2020-1-102       0.000000      Bajo    1
2      6  2020-1-103       0.751468      Alto    1
3      0  2020-1-104       0.000000      Bajo    2
4      0  2020-1-105       0.000000      Bajo    2

In [66]:
print(f'Demo shape: {demo.shape}, temp_precip shape: {temp_precip.shape}, expected shape: {(temp_precip.shape[0], demo.shape[1] + temp_precip.shape[1] - 1)}')

Demo shape: (26076, 5), temp_precip shape: (19932, 14), expected shape: (19932, 18)

In [67]:
df = pd.merge(demo, temp_precip, on='week-canton', how='right')

In [68]:
df.shape

(19932, 18)

In [69]:
df.head()

,casos,week-canton,relative_risk,classi_rr,urb,tmax_min,tmax_max,tmax_mean,tmax_median,tmin_min,tmin_max,tmin_mean,tmin_median,precip_total,precip_min,precip_max,precip_mean,precip_median
0,2,2020-1-507,3.011235,Alto,0,31.206179,34.216175,32.980368,33.278346,31.206179,34.216175,32.980368,33.278346,16.483572,0.0,8.394386,0.686816,0.0
1,0,2020-1-112,0.000000,Bajo,2,27.300568,31.489710,28.930743,28.016085,27.300568,31.489710,28.930743,28.016085,77.464812,0.0,37.667015,6.455401,0.0
2,29,2020-1-201,2.763229,Alto,1,21.756056,29.411386,26.367157,27.010843,21.756056,29.411386,26.367157,27.010843,56.828430,0.0,32.674007,3.551777,0.0
3,4,2020-1-110,1.288112,Alto,1,23.514788,24.153862,23.886117,23.937909,23.514788,24.153862,23.886117,23.937909,11.819548,0.0,11.819548,2.954887,0.0
4,0,2020-1-306,0.000000,Bajo,2,23.673475,24.585056,24.102187,24.075108,23.673475,24.585056,24.102187,24.075108,27.596506,0.0,27.596506,6.899127,0.0

In [70]:
df.dtypes

casos              int64
week-canton          str
relative_risk    float64
classi_rr            str
urb                int64
tmax_min         float64
tmax_max         float64
tmax_mean        float64
tmax_median      float64
tmin_min         float64
tmin_max         float64
tmin_mean        float64
tmin_median      float64
precip_total     float64
precip_min       float64
precip_max       float64
precip_mean      float64
precip_median    float64
dtype: object

In [71]:
df['urb'] = df['urb'].astype('category')

In [72]:
df.dtypes

casos               int64
week-canton           str
relative_risk     float64
classi_rr             str
urb              category
tmax_min          float64
tmax_max          float64
tmax_mean         float64
tmax_median       float64
tmin_min          float64
tmin_max          float64
tmin_mean         float64
tmin_median       float64
precip_total      float64
precip_min        float64
precip_max        float64
precip_mean       float64
precip_median     float64
dtype: object

In [73]:
df.to_csv('../../data/clean/full_data.csv', index=False)