# Integration of variables and cases

In [1]:
import pandas as pd

In [36]:
# REGULAR
cases = pd.read_csv('../../data/clean/casos_dengue.csv')

rr = pd.read_csv('../../data/clean/relative_risk.csv')

ndvi = pd.read_csv('../../data/clean/NDVI_int.csv')
ndvi.drop(columns=["Unnamed: 0"], inplace=True)
# lst = pd.read_csv('../../data/clean/LST_int.csv')
tmax = pd.read_csv('../../data/clean/tmax_weekly.csv')
tmax.drop(columns=["Unnamed: 0"], inplace=True)

tmin = pd.read_csv('../../data/clean/tmin_weekly.csv')
tmin.drop(columns=["Unnamed: 0"], inplace=True)

temp_prom = pd.read_csv('../../data/clean/temp_prom.csv')
temp_prom.drop(columns=["Unnamed: 0"], inplace=True)

sst = pd.read_csv('../../data/clean/SST_int.csv')
sst.drop(columns=["Unnamed: 0"], inplace=True)

# temp_min = pd.read_csv('../../data/clean/TNA_int.csv')

precip = pd.read_csv('../../data/clean/precip_weekly.csv')
precip.drop(columns=["Unnamed: 0"], inplace=True)

urb = pd.read_csv('../../data/clean/urbanization.csv')

In [37]:
# LAGS
cases_lags = pd.read_csv('../../data/clean/lags/casos_dengue_lags.csv')
cases_lags.drop(columns=["Unnamed: 0"], inplace=True)

rr_lags = pd.read_csv('../../data/clean/lags/relative_risk_lags.csv')
rr_lags.drop(columns=["Unnamed: 0"], inplace=True)

ndvi_lags = pd.read_csv('../../data/clean/lags/NDVI_lags.csv')
ndvi_lags.drop(columns=["Unnamed: 0"], inplace=True)

# lst_lags = pd.read_csv('../../data/clean/LST_int.csv')

tmax_lags = pd.read_csv('../../data/clean/lags/tmax_lags.csv')
tmax_lags.drop(columns=["Unnamed: 0"], inplace=True)

tmin_lags = pd.read_csv('../../data/clean/lags/tmin_lags.csv')
tmin_lags.drop(columns=["Unnamed: 0"], inplace=True)

temp_prom_lags = pd.read_csv('../../data/clean/lags/temp_prom_lags.csv')
temp_prom_lags.drop(columns=["Unnamed: 0"], inplace=True)

sst_lags = pd.read_csv('../../data/clean/lags/sst_lags.csv')
sst_lags.drop(columns=["Unnamed: 0"], inplace=True)

# temp_min = pd.read_csv('../../data/clean/TNA_int.csv')

precip_lags = pd.read_csv('../../data/clean/lags/precip_lags.csv')
precip_lags.drop(columns=["Unnamed: 0"], inplace=True)

In [38]:
cases.rename(columns = {"week-canton": "week_canton"}, inplace=True)

In [39]:
cases.head()

   casos week_canton
0    168    2020-1-0
1    171    2020-2-0
2    160    2020-3-0
3    154    2020-4-0
4    179    2020-5-0

In [40]:
no_total = ~cases['week_canton'].str.endswith("-0")
cases = cases[no_total]
no_total = ~cases['week_canton'].str.endswith("-1")
cases = cases[no_total]
no_total = ~cases['week_canton'].str.endswith("-2")
cases = cases[no_total]
no_total = ~cases['week_canton'].str.endswith("-3")
cases = cases[no_total]
no_total = ~cases['week_canton'].str.endswith("-4")
cases = cases[no_total]
no_total = ~cases['week_canton'].str.endswith("-5")
cases = cases[no_total]
no_total = ~cases['week_canton'].str.endswith("-6")
cases = cases[no_total]
no_total = ~cases['week_canton'].str.endswith("-7")
cases = cases[no_total]
no_total = ~cases['week_canton'].str.endswith("-99")
cases = cases[no_total]
no_total = ~cases['week_canton'].str.endswith("-98")
cases = cases[no_total]

In [41]:
no_total = ~cases['week_canton'].str.startswith("2020-53")
cases = cases[no_total]
no_total = ~cases['week_canton'].str.startswith("2021-53")
cases = cases[no_total]
no_total = ~cases['week_canton'].str.startswith("2022-53")
cases = cases[no_total]
no_total = ~cases['week_canton'].str.startswith("2023-53")
cases = cases[no_total]
no_total = ~cases['week_canton'].str.startswith("2024-53")
cases = cases[no_total]
no_total = ~cases['week_canton'].str.startswith("2025-53")
cases = cases[no_total]

In [42]:
cases.isna().sum()

casos          0
week_canton    0
dtype: int64

In [43]:
rr.rename(columns = {"week-canton": "week_canton"}, inplace=True)

In [44]:
rr.head()

         rr week_canton clasi_rr
0  0.258311  2020-1-101    Medio
1  0.930583  2020-2-101     Alto
2  1.356304  2020-3-101     Alto
3  0.657643  2020-4-101     Alto
4  0.000000  2020-5-101     Bajo

In [45]:
rr.isna().sum()

rr             0
week_canton    0
clasi_rr       0
dtype: int64

In [46]:
tmax.head()

   tmax_mean week_canton
0  33.578913  2020-1-507
1  33.366886  2020-2-507
2  33.510193  2020-3-507
3  33.203586  2020-4-507
4  33.583772  2020-5-507

In [47]:
tmax.isna().sum()

tmax_mean      0
week_canton    0
dtype: int64

In [48]:
semanas_nan_tmax = tmax[tmax.isna().any(axis=1)]["week_canton"]
semanas_nan_tmax[~semanas_nan_tmax.str.endswith("-607")]

Series([], Name: week_canton, dtype: str)

In [49]:
tmin.head()

   tmin_mean week_canton
0  24.814801  2020-1-507
1  25.734802  2020-2-507
2  26.134207  2020-3-507
3  24.225476  2020-4-507
4  24.872407  2020-5-507

In [50]:
tmin.isna().sum()

tmin_mean      0
week_canton    0
dtype: int64

In [51]:
temp_prom.isna().sum()

temp_prom      0
week_canton    0
dtype: int64

In [19]:
precip.head()

,precip_total,precip_max,precip_min,precip_mean,precip_median,week_canton
0,3.039511,3.039511,0.0,0.607902,0.0,2020-1-507
1,0.000000,0.000000,0.0,0.000000,0.0,2020-2-507
2,0.000000,0.000000,0.0,0.000000,0.0,2020-3-507
3,0.899132,0.599422,0.0,0.128447,0.0,2020-4-507
4,1.259273,1.259273,0.0,0.179896,0.0,2020-5-507

In [20]:
precip.isna().sum()

precip_total     0
precip_max       0
precip_min       0
precip_mean      0
precip_median    0
week_canton      0
dtype: int64

In [21]:
precip["week_canton"][precip["precip_min"].isna()]

Series([], Name: week_canton, dtype: str)

In [22]:
semanas_nan_precip = precip[precip.isna().any(axis=1)]["week_canton"]
semanas_nan_precip[~semanas_nan_precip.str.endswith("-607")]

Series([], Name: week_canton, dtype: str)

In [23]:
precip[precip["week_canton"].str.startswith("2025-40")]

,precip_total,precip_max,precip_min,precip_mean,precip_median,week_canton
299,240.914467,55.858140,18.050646,34.416352,37.238758,2025-40-507
611,232.371781,57.522236,0.000000,33.195969,38.348156,2025-40-112
923,188.127798,38.720340,16.623219,26.875400,19.360170,2025-40-201
1235,173.430051,39.985626,11.160120,24.775722,19.992813,2025-40-110
1547,85.755213,31.101759,0.000000,12.250745,15.550880,2025-40-306
...,...,...,...,...,...,...
24323,68.548032,33.105145,0.000000,9.792576,7.088577,2025-40-305
24635,167.043649,77.748040,0.000000,23.863378,15.549608,2025-40-116
24947,145.705608,36.266304,0.000000,20.815087,18.133152,2025-40-213
25259,146.740547,44.235374,0.000000,20.962935,22.117687,2025-40-111
25571,187.984196,41.262188,0.000000,26.854885,41.262188,2025-40-211

In [25]:
ndvi.head()

  week_canton    ndvi
0  2020-1-201  0.8913
1  2020-1-205  0.7437
2  2020-1-203  0.7113
3  2020-1-215  0.7439
4  2020-1-214  0.7885

In [26]:
ndvi.isna().sum()

week_canton    0
ndvi           0
dtype: int64

In [27]:
#lst.drop(columns=["Unnamed: 0"], inplace=True)
#lst.head()

In [28]:
sst.head()

  week_canton  nino34ssta
0  2020-1-101    0.535371
1  2020-1-102    0.535371
2  2020-1-103    0.535371
3  2020-1-104    0.535371
4  2020-1-105    0.535371

In [29]:
sst.isna().sum()

week_canton    0
nino34ssta     0
dtype: int64

In [30]:
urb.head()

   urb week_canton
0    1  2020-1-101
1    1  2020-1-102
2    1  2020-1-103
3    2  2020-1-104
4    2  2020-1-105

In [31]:
urb.isna().sum()

urb            0
week_canton    0
dtype: int64

In [52]:
urb[urb["week_canton"].str.contains("-53")]

       urb  week_canton
4264     1  2020-53-101
4265     1  2020-53-102
4266     1  2020-53-103
4267     2  2020-53-104
4268     2  2020-53-105
...    ...          ...
26071    0  2025-53-702
26072    0  2025-53-703
26073    0  2025-53-704
26074    0  2025-53-705
26075    2  2025-53-706

[492 rows x 2 columns]

In [54]:
no_total = ~urb['week_canton'].str.contains("-53")
urb = urb[no_total]
no_total = ~urb['week_canton'].str.contains("-53")
urb = urb[no_total]
no_total = ~urb['week_canton'].str.contains("-53")
urb = urb[no_total]
no_total = ~urb['week_canton'].str.contains("-53")
urb = urb[no_total]
no_total = ~urb['week_canton'].str.contains("-53")
urb = urb[no_total]
no_total = ~urb['week_canton'].str.contains("-53")
urb = urb[no_total]
no_total = ~urb['week_canton'].str.contains("-53")
urb = urb[no_total]
no_total = ~urb['week_canton'].str.contains("-53")
urb = urb[no_total]
no_total = ~urb['week_canton'].str.contains("-53")
urb = urb[no_total]
no_total = ~urb['week_canton'].str.contains("-53")
urb = urb[no_total]

In [55]:
urb.shape

(25584, 2)

In [56]:
# Dimensions

print(f"""
      cases: {cases.shape}
      rr: {rr.shape}
      ndvi: {ndvi.shape}
      tmax: {tmax.shape}
      tmin: {tmin.shape}
      sst: {sst.shape}
      precip: {precip.shape}
      urb: {urb.shape}
      """)

      cases: (25584, 2)
      rr: (25584, 3)
      ndvi: (25584, 2)
      tmax: (25584, 2)
      tmin: (25584, 2)
      sst: (25584, 2)
      precip: (25584, 6)
      urb: (25584, 2)

# Lags

In [57]:
cases_lags.isna().sum()

week_canton    0
casos_lag_8    0
casos_lag_7    0
casos_lag_6    0
casos_lag_5    0
casos_lag_4    0
casos_lag_3    0
casos_lag_2    0
casos_lag_1    0
dtype: int64

In [58]:
rr_lags.isna().sum()

week_canton       0
rr_lag_8          0
rr_lag_7          0
rr_lag_6          0
rr_lag_5          0
rr_lag_4          0
rr_lag_3          0
rr_lag_2          0
rr_lag_1          0
clasi_rr_lag_8    0
clasi_rr_lag_7    0
clasi_rr_lag_6    0
clasi_rr_lag_5    0
clasi_rr_lag_4    0
clasi_rr_lag_3    0
clasi_rr_lag_2    0
clasi_rr_lag_1    0
dtype: int64

In [59]:
ndvi_lags.isna().sum()

week_canton    0
ndvi_lag_8     0
ndvi_lag_7     0
ndvi_lag_6     0
ndvi_lag_5     0
ndvi_lag_4     0
ndvi_lag_3     0
ndvi_lag_2     0
ndvi_lag_1     0
dtype: int64

In [60]:
tmax_lags.isna().sum()

week_canton        0
tmax_mean_lag_8    0
tmax_mean_lag_7    0
tmax_mean_lag_6    0
tmax_mean_lag_5    0
tmax_mean_lag_4    0
tmax_mean_lag_3    0
tmax_mean_lag_2    0
tmax_mean_lag_1    0
dtype: int64

In [61]:
semanas_nan_tmax_lags = tmax_lags[tmax_lags.isna().any(axis=1)]["week_canton"]
semanas_nan_tmax_lags[~semanas_nan_tmax_lags.str.endswith("-607")]

Series([], Name: week_canton, dtype: str)

In [62]:
precip_lags.isna().sum()

week_canton            0
precip_total_lag_8     0
precip_total_lag_7     0
precip_total_lag_6     0
precip_total_lag_5     0
precip_total_lag_4     0
precip_total_lag_3     0
precip_total_lag_2     0
precip_total_lag_1     0
precip_max_lag_8       0
precip_max_lag_7       0
precip_max_lag_6       0
precip_max_lag_5       0
precip_max_lag_4       0
precip_max_lag_3       0
precip_max_lag_2       0
precip_max_lag_1       0
precip_mean_lag_8      0
precip_mean_lag_7      0
precip_mean_lag_6      0
precip_mean_lag_5      0
precip_mean_lag_4      0
precip_mean_lag_3      0
precip_mean_lag_2      0
precip_mean_lag_1      0
precip_median_lag_8    0
precip_median_lag_7    0
precip_median_lag_6    0
precip_median_lag_5    0
precip_median_lag_4    0
precip_median_lag_3    0
precip_median_lag_2    0
precip_median_lag_1    0
precip_min_lag_8       0
precip_min_lag_7       0
precip_min_lag_6       0
precip_min_lag_5       0
precip_min_lag_4       0
precip_min_lag_3       0
precip_min_lag_2       0
precip_min_lag_1       0
dtype: int64

In [63]:
tmin_lags.isna().sum()

week_canton        0
tmin_mean_lag_8    0
tmin_mean_lag_7    0
tmin_mean_lag_6    0
tmin_mean_lag_5    0
tmin_mean_lag_4    0
tmin_mean_lag_3    0
tmin_mean_lag_2    0
tmin_mean_lag_1    0
dtype: int64

In [64]:
temp_prom_lags.isna().sum()

week_canton        0
temp_prom_lag_8    0
temp_prom_lag_7    0
temp_prom_lag_6    0
temp_prom_lag_5    0
temp_prom_lag_4    0
temp_prom_lag_3    0
temp_prom_lag_2    0
temp_prom_lag_1    0
dtype: int64

In [82]:
sst_lags.isna().sum()

week_canton         0
nino34ssta_lag_8    0
nino34ssta_lag_7    0
nino34ssta_lag_6    0
nino34ssta_lag_5    0
nino34ssta_lag_4    0
nino34ssta_lag_3    0
nino34ssta_lag_2    0
nino34ssta_lag_1    0
dtype: int64

# Join

In [105]:
print(f'Temp max shape: {tmax.shape}, temp min shape: {tmin.shape}')

Temp max shape: (25584, 2), temp min shape: (25584, 2)

In [106]:
temp = pd.merge(tmin, tmax, on='week_canton', how='inner')
temp = pd.merge(temp, temp_prom, on='week_canton', how='inner')

In [107]:
temp.shape

(25584, 4)

In [108]:
temp.head()

   tmin_mean week_canton  tmax_mean  temp_prom
0  24.814801  2020-1-507  33.578913  29.196857
1  25.734802  2020-2-507  33.366886  29.550844
2  26.134207  2020-3-507  33.510193  29.822200
3  24.225476  2020-4-507  33.203586  28.714531
4  24.872407  2020-5-507  33.583772  29.228089

In [109]:
print(f'Temp shape: {temp.shape}, precip shape: {precip.shape}')

Temp shape: (25584, 4), precip shape: (25584, 6)

In [110]:
temp_precip = pd.merge(temp, precip, on='week_canton', how='inner')

In [111]:
temp_precip.shape

(25584, 9)

In [72]:
temp_precip.head()

,tmin_mean,week_canton,tmax_mean,temp_prom,precip_total,precip_max,precip_min,precip_mean,precip_median
0,24.814801,2020-1-507,33.578913,29.196857,3.039511,3.039511,0.0,0.607902,0.0
1,25.734802,2020-2-507,33.366886,29.550844,0.000000,0.000000,0.0,0.000000,0.0
2,26.134207,2020-3-507,33.510193,29.822200,0.000000,0.000000,0.0,0.000000,0.0
3,24.225476,2020-4-507,33.203586,28.714531,0.899132,0.599422,0.0,0.128447,0.0
4,24.872407,2020-5-507,33.583772,29.228089,1.259273,1.259273,0.0,0.179896,0.0

In [112]:
print(f'Cases shape: {cases.shape}, rr shape: {rr.shape}, urb shape: {urb.shape}')

Cases shape: (25584, 2), rr shape: (25584, 3), urb shape: (25584, 2)

In [113]:
cases_rr = pd.merge(cases, rr, on=['week_canton'], how='inner')

In [114]:
cases_rr.shape

(25584, 4)

In [116]:
urb.head()

   urb week_canton
0    1  2020-1-101
1    1  2020-1-102
2    1  2020-1-103
3    2  2020-1-104
4    2  2020-1-105

In [117]:
demo = pd.merge(cases_rr, urb, on='week_canton', how='inner')

In [118]:
demo.shape

(25584, 5)

In [119]:
demo.head()

   casos week_canton        rr clasi_rr  urb
0      3  2020-1-101  0.258311    Medio    1
1     11  2020-2-101  0.930583     Alto    1
2     15  2020-3-101  1.356304     Alto    1
3      7  2020-4-101  0.657643     Alto    1
4      0  2020-5-101  0.000000     Bajo    1

In [120]:
print(f'Demo shape: {demo.shape}, temp_precip shape: {temp_precip.shape}, expected shape: {(temp_precip.shape[0], demo.shape[1] + temp_precip.shape[1] - 1)}')

Demo shape: (25584, 5), temp_precip shape: (25584, 9), expected shape: (25584, 13)

In [121]:
demo_temp_precip = pd.merge(demo, temp_precip, on='week_canton', how='inner')

In [122]:
demo_temp_precip.shape

(25584, 13)

In [123]:
sst_ndvi = pd.merge(sst, ndvi, on='week_canton', how='inner')

In [124]:
sst_ndvi.shape

(25584, 3)

In [125]:
df_no_lag = pd.merge(demo_temp_precip, sst_ndvi, on='week_canton', how='inner')

In [126]:
df_no_lag.shape

(25584, 15)

In [127]:
cases_lags.shape

(24928, 9)

In [128]:
df_lag1 = pd.merge(df_no_lag, cases_lags, on='week_canton', how='inner')

In [129]:
df_lag1.shape # expected for the 8 years of missing data for 299 weeks

(24928, 23)

In [130]:
df_lag2 = pd.merge(df_lag1, rr_lags, on='week_canton', how='inner')
df_lag3 = pd.merge(df_lag2, ndvi_lags, on='week_canton', how='inner')
df_lag4 = pd.merge(df_lag3, tmax_lags, on='week_canton', how='inner')
df_lag5 = pd.merge(df_lag4, tmin_lags, on='week_canton', how='inner')
df_lag6 = pd.merge(df_lag5, sst_lags, on='week_canton', how='inner')
df_lag7 = pd.merge(df_lag6, temp_prom_lags, on='week_canton', how='inner')
df = pd.merge(df_lag7, precip_lags, on='week_canton', how='inner')

In [131]:
df.shape

(24928, 119)

In [132]:
df.head()

,casos,week_canton,rr,clasi_rr,urb,tmin_mean,tmax_mean,temp_prom,precip_total,precip_max,...,precip_median_lag_2,precip_median_lag_1,precip_min_lag_8,precip_min_lag_7,precip_min_lag_6,precip_min_lag_5,precip_min_lag_4,precip_min_lag_3,precip_min_lag_2,precip_min_lag_1
0,4,2020-9-101,0.459451,Medio,1,18.775265,27.372263,23.073764,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2,2020-10-101,0.224397,Medio,1,18.723231,27.568323,23.145777,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2,2020-11-101,0.253939,Medio,1,19.110772,27.610641,23.360707,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0,2020-12-101,0.000000,Bajo,1,18.967383,27.361927,23.164655,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0,2020-13-101,0.000000,Bajo,1,18.653528,27.606657,23.130092,1.409859,1.409859,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [133]:
df.dtypes

casos                 int64
week_canton             str
rr                  float64
clasi_rr                str
urb                   int64
                     ...
precip_min_lag_5    float64
precip_min_lag_4    float64
precip_min_lag_3    float64
precip_min_lag_2    float64
precip_min_lag_1    float64
Length: 119, dtype: object

In [134]:
df['urb'] = df['urb'].astype('category')
df['clasi_rr'] = df['clasi_rr'].astype('category')
df['clasi_rr_lag_1'] = df['clasi_rr_lag_1'].astype('category')
df['clasi_rr_lag_2'] = df['clasi_rr_lag_2'].astype('category')
df['clasi_rr_lag_3'] = df['clasi_rr_lag_3'].astype('category')
df['clasi_rr_lag_4'] = df['clasi_rr_lag_4'].astype('category')
df['clasi_rr_lag_5'] = df['clasi_rr_lag_5'].astype('category')
df['clasi_rr_lag_6'] = df['clasi_rr_lag_6'].astype('category')
df['clasi_rr_lag_7'] = df['clasi_rr_lag_7'].astype('category')
df['clasi_rr_lag_8'] = df['clasi_rr_lag_8'].astype('category')

In [135]:
df.dtypes

casos                  int64
week_canton              str
rr                   float64
clasi_rr            category
urb                 category
                      ...
precip_min_lag_5     float64
precip_min_lag_4     float64
precip_min_lag_3     float64
precip_min_lag_2     float64
precip_min_lag_1     float64
Length: 119, dtype: object

In [136]:
df.to_csv('../../data/clean/full_data.csv', index=False)