# Integration of variables and cases

In [28]:
import pandas as pd

In [29]:
cases = pd.read_csv('../../data/clean/casos_dengue.csv')
rr = pd.read_csv('../../data/clean/relative_risk.csv')
temp_max = pd.read_csv('../../data/clean/tmax_weekly.csv')
temp_min = pd.read_csv('../../data/clean/tmin_weekly.csv')
precip = pd.read_csv('../../data/clean/chirps_precip_weekly.csv')

In [30]:
cases.head()

,semana,0,1,101,102,103,104,105,106,107,...,611,7,701,702,703,704,705,706,99,98
0,1,168,22,3,0,6,0,0,1,3,...,0,49,3,19,12,5,1,9,0,0
1,2,171,30,11,0,5,1,0,3,3,...,1,52,5,25,8,3,2,9,0,0
2,3,160,24,15,0,3,0,0,1,1,...,2,35,0,16,3,1,2,13,0,0
3,4,154,18,7,0,2,4,0,0,2,...,1,30,4,9,7,3,2,5,0,0
4,5,179,9,0,0,4,0,0,0,0,...,0,44,4,13,16,1,0,10,0,0

In [31]:
rr.head()

,0,1,101,102,103,104,105,106,107,108,...,611,7,701,702,703,704,705,706,99,98
0,1.0,0.127456,0.017576,0.0,0.051568,0.000000,0.0,0.007451,0.030879,0.000000,...,0.000000,0.330581,0.024723,0.131419,0.076127,0.031300,0.006652,0.065014,0.0,0.0
1,1.0,0.169629,0.046494,0.0,0.028178,0.006232,0.0,0.011736,0.012556,0.005599,...,0.004356,0.312110,0.024499,0.127054,0.044138,0.011790,0.013367,0.054595,0.0,0.0
2,1.0,0.117340,0.089635,0.0,0.015764,0.000000,0.0,0.005650,0.005325,0.000000,...,0.010836,0.293209,0.000000,0.090402,0.018329,0.007835,0.011419,0.063205,0.0,0.0
3,1.0,0.181341,0.049058,0.0,0.017940,0.029785,0.0,0.000000,0.014933,0.000000,...,0.008825,0.245396,0.030746,0.057354,0.063098,0.028153,0.017823,0.031353,0.0,0.0
4,1.0,0.062895,0.000000,0.0,0.017940,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.293098,0.025883,0.079564,0.106397,0.004775,0.000000,0.055543,0.0,0.0

In [32]:
temp_max.head()

   points        week  temp_week_max  longitude  latitude   canton
0       0  2020-01-05      33.828182 -83.301849   8.39857  Golfito
1       0  2020-01-12      34.763752 -83.301849   8.39857  Golfito
2       0  2020-01-19      35.184273 -83.301849   8.39857  Golfito
3       0  2020-01-26      34.391785 -83.301849   8.39857  Golfito
4       0  2020-02-02      34.843080 -83.301849   8.39857  Golfito

In [33]:
temp_min.head()

   points        week  temp_week_min  longitude  latitude   canton
0       0  2020-01-05      31.307518 -83.301849   8.39857  Golfito
1       0  2020-01-12      31.340557 -83.301849   8.39857  Golfito
2       0  2020-01-19      32.219620 -83.301849   8.39857  Golfito
3       0  2020-01-26      30.882504 -83.301849   8.39857  Golfito
4       0  2020-02-02      31.125221 -83.301849   8.39857  Golfito

In [34]:
precip.head()

,week,latitude,longitude,prep_week_min,prep_week_max,prep_week_mean,prep_week_median,prep_week_sum,lon,lat,canton
0,2020-01-05,8.374996,-83.325005,0.0,11.985470,4.794188,0.000000,23.97094,-83.301849,8.39857,Golfito
1,2020-01-12,8.374996,-83.325005,0.0,0.000000,0.000000,0.000000,0.00000,-83.301849,8.39857,Golfito
2,2020-01-19,8.374996,-83.325005,0.0,0.000000,0.000000,0.000000,0.00000,-83.301849,8.39857,Golfito
3,2020-01-26,8.374996,-83.325005,0.0,20.163061,7.512413,5.040765,52.58689,-83.301849,8.39857,Golfito
4,2020-02-02,8.374996,-83.325005,0.0,43.318928,9.282628,0.000000,64.97839,-83.301849,8.39857,Golfito

## Group by simple

In [41]:
temp_max_gr = temp_max.groupby(["canton", "week"])["temp_week_max"].mean().reset_index()

In [36]:
temp_max_gr.head()

      canton        week  temp_week_max
0  Abangares  2020-01-05      33.268527
1  Abangares  2020-01-12      33.918579
2  Abangares  2020-01-19      33.467564
3  Abangares  2020-01-26      34.116432
4  Abangares  2020-02-02      34.634647

In [37]:
temp_max_gr["canton"].unique()

<StringArray>
[          'Abangares',              'Acosta',            'Alajuela',
          'Alajuelita',            'Alvarado',              'Aserrí',
              'Atenas',             'Bagaces',               'Barva',
        'Buenos Aires',            'Carrillo',             'Cartago',
               'Cañas',          'Corredores',           'Coto Brus',
                'Dota',           'El Guarco',             'Esparza',
            'Garabito',             'Golfito',              'Grecia',
             'Guatuso',             'Guácimo',             'Heredia',
            'Hojancha',             'Jiménez',             'La Cruz',
            'La Unión',  'León Cortés Castro',             'Liberia',
               'Limón',          'Los Chiles',              'Matina',
       'Montes de Oro',                'Mora',           'Nandayure',
             'Naranjo',              'Nicoya',            'Oreamuno',
             'Orotina',                 'Osa',             'Paraíso',
             'Parrita',              'Pococí',          'Puntarenas',
            'Puriscal',       'Pérez Zeledón',              'Quepos',
          'Río Cuarto',          'San Carlos',           'San Mateo',
           'San Pablo',           'San Ramón',           'Santa Ana',
          'Santa Cruz',           'Sarapiquí',              'Sarchí',
           'Siquirres',           'Talamanca',             'Tarrazú',
             'Tilarán',           'Turrialba',          'Turrubares',
               'Upala', 'Vázquez de Coronado',             'Zarcero']
Length: 66, dtype: str

In [43]:
temp_max_gr["canton"] = temp_max_gr["canton"].replace({"Abangares": 507, 'Acosta': 112, 'Alajuela': 201, 'Alajuelita': 110, 'Alvarado': 306, 'Aserrí': 106, 'Atenas': 205, 'Bagaces': 504, 'Barva': 402, 'Buenos Aires': 603, 'Carrillo': 505, 'Cartago': 301, 'Cañas': 506,     'Corredores': 610, 'Coto Brus': 608, 'Dota': 117, 'El Guarco': 308, 'Esparza': 602, 'Garabito': 611, 'Golfito': 607, 'Grecia': 203, 'Guatuso': 215, 'Guácimo': 706, 'Heredia': 401, 'Hojancha': 511, 'Jiménez': 304, 'La Cruz': 510, 'La Unión': 303, 'León Cortés Castro': 120, 'Liberia': 501, 'Limón': 701, 'Los Chiles': 214, 'Matina': 705, 'Montes de Oro': 604, 'Mora': 107, 'Nandayure': 509, 'Naranjo': 206, 'Nicoya': 502, 'Oreamuno': 307, 'Orotina': 209, 'Osa': 605, 'Paraíso': 302, 'Parrita': 609, 'Pococí': 702, 'Puntarenas': 601, 'Puriscal': 104, 'Pérez Zeledón': 119, 'Quepos': 606, 'Río Cuarto': 216, 'San Carlos': 210, 'San Mateo': 204, 'San Pablo': 409, 'San Ramón': 202,     'Santa Ana': 109, 'Santa Cruz': 503, 'Sarapiquí': 410, 'Sarchí': 212, 'Siquirres': 703, 'Talamanca': 704, 'Tarrazú': 105, 'Tilarán': 508, 'Turrialba': 305, 'Turrubares': 116, 'Upala': 213, 'Vázquez de Coronado': 111, 'Zarcero': 211})

In [46]:
temp_max_gr["canton"].unique()

array([507, 112, 201, 110, 306, 106, 205, 504, 402, 603, 505, 301, 506,
       610, 608, 117, 308, 602, 611, 607, 203, 215, 706, 401, 511, 304,
       510, 303, 120, 501, 701, 214, 705, 604, 107, 509, 206, 502, 307,
       209, 605, 302, 609, 702, 601, 104, 119, 606, 216, 210, 204, 409,
       202, 109, 503, 410, 212, 703, 704, 105, 508, 305, 116, 213, 111,
       211], dtype=object)

In [48]:
temp_min_gr = temp_min.groupby(["canton", "week"])["temp_week_min"].mean().reset_index()
precip_min = precip.groupby(["canton", "week"])["prep_week_min"].mean().reset_index()
precip_max = precip.groupby(["canton", "week"])["prep_week_max"].mean().reset_index()
precip_mean = precip.groupby(["canton", "week"])["prep_week_mean"].mean().reset_index()
precip_median = precip.groupby(["canton", "week"])["prep_week_median"].mean().reset_index()

In [49]:
temp_min_gr["canton"] = temp_min_gr["canton"].replace({"Abangares": 507, 'Acosta': 112, 'Alajuela': 201, 'Alajuelita': 110, 'Alvarado': 306, 'Aserrí': 106, 'Atenas': 205, 'Bagaces': 504, 'Barva': 402, 'Buenos Aires': 603, 'Carrillo': 505, 'Cartago': 301, 'Cañas': 506,     'Corredores': 610, 'Coto Brus': 608, 'Dota': 117, 'El Guarco': 308, 'Esparza': 602, 'Garabito': 611, 'Golfito': 607, 'Grecia': 203, 'Guatuso': 215, 'Guácimo': 706, 'Heredia': 401, 'Hojancha': 511, 'Jiménez': 304, 'La Cruz': 510, 'La Unión': 303, 'León Cortés Castro': 120, 'Liberia': 501, 'Limón': 701, 'Los Chiles': 214, 'Matina': 705, 'Montes de Oro': 604, 'Mora': 107, 'Nandayure': 509, 'Naranjo': 206, 'Nicoya': 502, 'Oreamuno': 307, 'Orotina': 209, 'Osa': 605, 'Paraíso': 302, 'Parrita': 609, 'Pococí': 702, 'Puntarenas': 601, 'Puriscal': 104, 'Pérez Zeledón': 119, 'Quepos': 606, 'Río Cuarto': 216, 'San Carlos': 210, 'San Mateo': 204, 'San Pablo': 409, 'San Ramón': 202,     'Santa Ana': 109, 'Santa Cruz': 503, 'Sarapiquí': 410, 'Sarchí': 212, 'Siquirres': 703, 'Talamanca': 704, 'Tarrazú': 105, 'Tilarán': 508, 'Turrialba': 305, 'Turrubares': 116, 'Upala': 213, 'Vázquez de Coronado': 111, 'Zarcero': 211})

precip_min["canton"] = precip_min["canton"].replace({"Abangares": 507, 'Acosta': 112, 'Alajuela': 201, 'Alajuelita': 110, 'Alvarado': 306, 'Aserrí': 106, 'Atenas': 205, 'Bagaces': 504, 'Barva': 402, 'Buenos Aires': 603, 'Carrillo': 505, 'Cartago': 301, 'Cañas': 506,     'Corredores': 610, 'Coto Brus': 608, 'Dota': 117, 'El Guarco': 308, 'Esparza': 602, 'Garabito': 611, 'Golfito': 607, 'Grecia': 203, 'Guatuso': 215, 'Guácimo': 706, 'Heredia': 401, 'Hojancha': 511, 'Jiménez': 304, 'La Cruz': 510, 'La Unión': 303, 'León Cortés Castro': 120, 'Liberia': 501, 'Limón': 701, 'Los Chiles': 214, 'Matina': 705, 'Montes de Oro': 604, 'Mora': 107, 'Nandayure': 509, 'Naranjo': 206, 'Nicoya': 502, 'Oreamuno': 307, 'Orotina': 209, 'Osa': 605, 'Paraíso': 302, 'Parrita': 609, 'Pococí': 702, 'Puntarenas': 601, 'Puriscal': 104, 'Pérez Zeledón': 119, 'Quepos': 606, 'Río Cuarto': 216, 'San Carlos': 210, 'San Mateo': 204, 'San Pablo': 409, 'San Ramón': 202,     'Santa Ana': 109, 'Santa Cruz': 503, 'Sarapiquí': 410, 'Sarchí': 212, 'Siquirres': 703, 'Talamanca': 704, 'Tarrazú': 105, 'Tilarán': 508, 'Turrialba': 305, 'Turrubares': 116, 'Upala': 213, 'Vázquez de Coronado': 111, 'Zarcero': 211})

precip_max["canton"] = precip_max["canton"].replace({"Abangares": 507, 'Acosta': 112, 'Alajuela': 201, 'Alajuelita': 110, 'Alvarado': 306, 'Aserrí': 106, 'Atenas': 205, 'Bagaces': 504, 'Barva': 402, 'Buenos Aires': 603, 'Carrillo': 505, 'Cartago': 301, 'Cañas': 506,     'Corredores': 610, 'Coto Brus': 608, 'Dota': 117, 'El Guarco': 308, 'Esparza': 602, 'Garabito': 611, 'Golfito': 607, 'Grecia': 203, 'Guatuso': 215, 'Guácimo': 706, 'Heredia': 401, 'Hojancha': 511, 'Jiménez': 304, 'La Cruz': 510, 'La Unión': 303, 'León Cortés Castro': 120, 'Liberia': 501, 'Limón': 701, 'Los Chiles': 214, 'Matina': 705, 'Montes de Oro': 604, 'Mora': 107, 'Nandayure': 509, 'Naranjo': 206, 'Nicoya': 502, 'Oreamuno': 307, 'Orotina': 209, 'Osa': 605, 'Paraíso': 302, 'Parrita': 609, 'Pococí': 702, 'Puntarenas': 601, 'Puriscal': 104, 'Pérez Zeledón': 119, 'Quepos': 606, 'Río Cuarto': 216, 'San Carlos': 210, 'San Mateo': 204, 'San Pablo': 409, 'San Ramón': 202,     'Santa Ana': 109, 'Santa Cruz': 503, 'Sarapiquí': 410, 'Sarchí': 212, 'Siquirres': 703, 'Talamanca': 704, 'Tarrazú': 105, 'Tilarán': 508, 'Turrialba': 305, 'Turrubares': 116, 'Upala': 213, 'Vázquez de Coronado': 111, 'Zarcero': 211})

precip_mean["canton"] = precip_mean["canton"].replace({"Abangares": 507, 'Acosta': 112, 'Alajuela': 201, 'Alajuelita': 110, 'Alvarado': 306, 'Aserrí': 106, 'Atenas': 205, 'Bagaces': 504, 'Barva': 402, 'Buenos Aires': 603, 'Carrillo': 505, 'Cartago': 301, 'Cañas': 506,     'Corredores': 610, 'Coto Brus': 608, 'Dota': 117, 'El Guarco': 308, 'Esparza': 602, 'Garabito': 611, 'Golfito': 607, 'Grecia': 203, 'Guatuso': 215, 'Guácimo': 706, 'Heredia': 401, 'Hojancha': 511, 'Jiménez': 304, 'La Cruz': 510, 'La Unión': 303, 'León Cortés Castro': 120, 'Liberia': 501, 'Limón': 701, 'Los Chiles': 214, 'Matina': 705, 'Montes de Oro': 604, 'Mora': 107, 'Nandayure': 509, 'Naranjo': 206, 'Nicoya': 502, 'Oreamuno': 307, 'Orotina': 209, 'Osa': 605, 'Paraíso': 302, 'Parrita': 609, 'Pococí': 702, 'Puntarenas': 601, 'Puriscal': 104, 'Pérez Zeledón': 119, 'Quepos': 606, 'Río Cuarto': 216, 'San Carlos': 210, 'San Mateo': 204, 'San Pablo': 409, 'San Ramón': 202,     'Santa Ana': 109, 'Santa Cruz': 503, 'Sarapiquí': 410, 'Sarchí': 212, 'Siquirres': 703, 'Talamanca': 704, 'Tarrazú': 105, 'Tilarán': 508, 'Turrialba': 305, 'Turrubares': 116, 'Upala': 213, 'Vázquez de Coronado': 111, 'Zarcero': 211})

precip_median["canton"] = precip_median["canton"].replace({"Abangares": 507, 'Acosta': 112, 'Alajuela': 201, 'Alajuelita': 110, 'Alvarado': 306, 'Aserrí': 106, 'Atenas': 205, 'Bagaces': 504, 'Barva': 402, 'Buenos Aires': 603, 'Carrillo': 505, 'Cartago': 301, 'Cañas': 506,     'Corredores': 610, 'Coto Brus': 608, 'Dota': 117, 'El Guarco': 308, 'Esparza': 602, 'Garabito': 611, 'Golfito': 607, 'Grecia': 203, 'Guatuso': 215, 'Guácimo': 706, 'Heredia': 401, 'Hojancha': 511, 'Jiménez': 304, 'La Cruz': 510, 'La Unión': 303, 'León Cortés Castro': 120, 'Liberia': 501, 'Limón': 701, 'Los Chiles': 214, 'Matina': 705, 'Montes de Oro': 604, 'Mora': 107, 'Nandayure': 509, 'Naranjo': 206, 'Nicoya': 502, 'Oreamuno': 307, 'Orotina': 209, 'Osa': 605, 'Paraíso': 302, 'Parrita': 609, 'Pococí': 702, 'Puntarenas': 601, 'Puriscal': 104, 'Pérez Zeledón': 119, 'Quepos': 606, 'Río Cuarto': 216, 'San Carlos': 210, 'San Mateo': 204, 'San Pablo': 409, 'San Ramón': 202,     'Santa Ana': 109, 'Santa Cruz': 503, 'Sarapiquí': 410, 'Sarchí': 212, 'Siquirres': 703, 'Talamanca': 704, 'Tarrazú': 105, 'Tilarán': 508, 'Turrialba': 305, 'Turrubares': 116, 'Upala': 213, 'Vázquez de Coronado': 111, 'Zarcero': 211})

In [ ]:
temp_min_gr["canton"].unique()

In [50]:
precip_min["canton"].unique()

array([507, 112, 201, 110, 306, 106, 205, 504, 402, 603, 505, 301, 506,
       610, 608, 117, 308, 602, 611, 607, 203, 215, 706, 401, 511, 304,
       510, 303, 120, 501, 701, 214, 705, 604, 107, 509, 206, 502, 307,
       209, 605, 302, 609, 702, 601, 104, 119, 606, 216, 210, 204, 409,
       202, 109, 503, 410, 212, 703, 704, 105, 508, 305, 116, 213, 111,
       211], dtype=object)

In [51]:
precip_max["canton"].unique()

array([507, 112, 201, 110, 306, 106, 205, 504, 402, 603, 505, 301, 506,
       610, 608, 117, 308, 602, 611, 607, 203, 215, 706, 401, 511, 304,
       510, 303, 120, 501, 701, 214, 705, 604, 107, 509, 206, 502, 307,
       209, 605, 302, 609, 702, 601, 104, 119, 606, 216, 210, 204, 409,
       202, 109, 503, 410, 212, 703, 704, 105, 508, 305, 116, 213, 111,
       211], dtype=object)

In [52]:
precip_mean["canton"].unique()

array([507, 112, 201, 110, 306, 106, 205, 504, 402, 603, 505, 301, 506,
       610, 608, 117, 308, 602, 611, 607, 203, 215, 706, 401, 511, 304,
       510, 303, 120, 501, 701, 214, 705, 604, 107, 509, 206, 502, 307,
       209, 605, 302, 609, 702, 601, 104, 119, 606, 216, 210, 204, 409,
       202, 109, 503, 410, 212, 703, 704, 105, 508, 305, 116, 213, 111,
       211], dtype=object)

In [53]:
precip_median["canton"].unique()

array([507, 112, 201, 110, 306, 106, 205, 504, 402, 603, 505, 301, 506,
       610, 608, 117, 308, 602, 611, 607, 203, 215, 706, 401, 511, 304,
       510, 303, 120, 501, 701, 214, 705, 604, 107, 509, 206, 502, 307,
       209, 605, 302, 609, 702, 601, 104, 119, 606, 216, 210, 204, 409,
       202, 109, 503, 410, 212, 703, 704, 105, 508, 305, 116, 213, 111,
       211], dtype=object)