# Integration of variables and cases

In [1]:
import pandas as pd

In [2]:
cases = pd.read_csv('../../data/clean/casos_dengue.csv')
rr = pd.read_csv('../../data/clean/relative_risk.csv')
temp_max = pd.read_csv('../../data/clean/tmax_weekly.csv')
temp_min = pd.read_csv('../../data/clean/tmin_weekly.csv')
precip = pd.read_csv('../../data/clean/precip_weekly.csv')
urb = pd.read_csv('../../data/clean/urbanization.csv')

In [3]:
cases.head()

   casos week-canton
0    168    2020-1-0
1    171    2020-2-0
2    160    2020-3-0
3    154    2020-4-0
4    179    2020-5-0

In [4]:
rr.head()

   casos week-canton
0    1.0    2020-1-0
1    1.0    2020-2-0
2    1.0    2020-3-0
3    1.0    2020-4-0
4    1.0    2020-5-0

In [5]:
temp_max.head()

,Unnamed: 0,canton,tmax_min,tmax_max,tmax_mean,tmax_median,week
0,1,Abangares,31.206179,34.216175,32.980368,33.278346,2020-1
1,2,Acosta,27.300568,31.489710,28.930743,28.016085,2020-1
2,3,Alajuela,21.756056,29.411386,26.367157,27.010843,2020-1
3,4,Alajuelita,23.514788,24.153862,23.886117,23.937909,2020-1
4,5,Alvarado,23.673475,24.585056,24.102187,24.075108,2020-1

In [6]:
temp_min.head()

,Unnamed: 0,canton,tmin_min,tmin_max,tmin_mean,tmin_median,week
0,1,Abangares,31.206179,34.216175,32.980368,33.278346,2020-1
1,2,Acosta,27.300568,31.489710,28.930743,28.016085,2020-1
2,3,Alajuela,21.756056,29.411386,26.367157,27.010843,2020-1
3,4,Alajuelita,23.514788,24.153862,23.886117,23.937909,2020-1
4,5,Alvarado,23.673475,24.585056,24.102187,24.075108,2020-1

In [7]:
precip.head()

,Unnamed: 0,canton,precip_total,precip_min,precip_max,precip_mean,precip_median,week
0,1,Abangares,16.483572,0.0,8.394386,0.686816,0.0,2020-1
1,2,Acosta,77.464812,0.0,37.667015,6.455401,0.0,2020-1
2,3,Alajuela,56.828430,0.0,32.674007,3.551777,0.0,2020-1
3,4,Alajuelita,11.819548,0.0,11.819548,2.954887,0.0,2020-1
4,5,Alvarado,27.596506,0.0,27.596506,6.899127,0.0,2020-1

# Create week-canton pairs

In [8]:
temp_max["canton"].unique()

<StringArray>
[          'Abangares',              'Acosta',            'Alajuela',
          'Alajuelita',            'Alvarado',              'Aserrí',
              'Atenas',             'Bagaces',               'Barva',
        'Buenos Aires',            'Carrillo',             'Cartago',
               'Cañas',          'Corredores',           'Coto Brus',
                'Dota',           'El Guarco',             'Esparza',
            'Garabito',             'Golfito',              'Grecia',
             'Guatuso',             'Guácimo',             'Heredia',
            'Hojancha',             'Jiménez',             'La Cruz',
            'La Unión',  'León Cortés Castro',             'Liberia',
               'Limón',          'Los Chiles',              'Matina',
       'Montes de Oro',                'Mora',           'Nandayure',
             'Naranjo',              'Nicoya',            'Oreamuno',
             'Orotina',                 'Osa',             'Paraíso',
             'Parrita',              'Pococí',          'Puntarenas',
            'Puriscal',       'Pérez Zeledón',              'Quepos',
          'Río Cuarto',          'San Carlos',           'San Mateo',
           'San Pablo',           'San Ramón',           'Santa Ana',
          'Santa Cruz',           'Sarapiquí',              'Sarchí',
           'Siquirres',           'Talamanca',             'Tarrazú',
             'Tilarán',           'Turrialba',          'Turrubares',
               'Upala', 'Vázquez de Coronado',             'Zarcero']
Length: 66, dtype: str

In [9]:
temp_min["canton"] = temp_min["canton"].replace({"Abangares": 507, 'Acosta': 112, 'Alajuela': 201, 'Alajuelita': 110, 'Alvarado': 306, 'Aserrí': 106, 'Atenas': 205, 'Bagaces': 504, 'Barva': 402, 'Buenos Aires': 603, 'Carrillo': 505, 'Cartago': 301, 'Cañas': 506,     'Corredores': 610, 'Coto Brus': 608, 'Dota': 117, 'El Guarco': 308, 'Esparza': 602, 'Garabito': 611, 'Golfito': 607, 'Grecia': 203, 'Guatuso': 215, 'Guácimo': 706, 'Heredia': 401, 'Hojancha': 511, 'Jiménez': 304, 'La Cruz': 510, 'La Unión': 303, 'León Cortés Castro': 120, 'Liberia': 501, 'Limón': 701, 'Los Chiles': 214, 'Matina': 705, 'Montes de Oro': 604, 'Mora': 107, 'Nandayure': 509, 'Naranjo': 206, 'Nicoya': 502, 'Oreamuno': 307, 'Orotina': 209, 'Osa': 605, 'Paraíso': 302, 'Parrita': 609, 'Pococí': 702, 'Puntarenas': 601, 'Puriscal': 104, 'Pérez Zeledón': 119, 'Quepos': 606, 'Río Cuarto': 216, 'San Carlos': 210, 'San Mateo': 204, 'San Pablo': 409, 'San Ramón': 202,     'Santa Ana': 109, 'Santa Cruz': 503, 'Sarapiquí': 410, 'Sarchí': 212, 'Siquirres': 703, 'Talamanca': 704, 'Tarrazú': 105, 'Tilarán': 508, 'Turrialba': 305, 'Turrubares': 116, 'Upala': 213, 'Vázquez de Coronado': 111, 'Zarcero': 211})
precip["canton"] = precip["canton"].replace({"Abangares": 507, 'Acosta': 112, 'Alajuela': 201, 'Alajuelita': 110, 'Alvarado': 306, 'Aserrí': 106, 'Atenas': 205, 'Bagaces': 504, 'Barva': 402, 'Buenos Aires': 603, 'Carrillo': 505, 'Cartago': 301, 'Cañas': 506,     'Corredores': 610, 'Coto Brus': 608, 'Dota': 117, 'El Guarco': 308, 'Esparza': 602, 'Garabito': 611, 'Golfito': 607, 'Grecia': 203, 'Guatuso': 215, 'Guácimo': 706, 'Heredia': 401, 'Hojancha': 511, 'Jiménez': 304, 'La Cruz': 510, 'La Unión': 303, 'León Cortés Castro': 120, 'Liberia': 501, 'Limón': 701, 'Los Chiles': 214, 'Matina': 705, 'Montes de Oro': 604, 'Mora': 107, 'Nandayure': 509, 'Naranjo': 206, 'Nicoya': 502, 'Oreamuno': 307, 'Orotina': 209, 'Osa': 605, 'Paraíso': 302, 'Parrita': 609, 'Pococí': 702, 'Puntarenas': 601, 'Puriscal': 104, 'Pérez Zeledón': 119, 'Quepos': 606, 'Río Cuarto': 216, 'San Carlos': 210, 'San Mateo': 204, 'San Pablo': 409, 'San Ramón': 202,     'Santa Ana': 109, 'Santa Cruz': 503, 'Sarapiquí': 410, 'Sarchí': 212, 'Siquirres': 703, 'Talamanca': 704, 'Tarrazú': 105, 'Tilarán': 508, 'Turrialba': 305, 'Turrubares': 116, 'Upala': 213, 'Vázquez de Coronado': 111, 'Zarcero': 211})
temp_max["canton"] = temp_max["canton"].replace({"Abangares": 507, 'Acosta': 112, 'Alajuela': 201, 'Alajuelita': 110, 'Alvarado': 306, 'Aserrí': 106, 'Atenas': 205, 'Bagaces': 504, 'Barva': 402, 'Buenos Aires': 603, 'Carrillo': 505, 'Cartago': 301, 'Cañas': 506,     'Corredores': 610, 'Coto Brus': 608, 'Dota': 117, 'El Guarco': 308, 'Esparza': 602, 'Garabito': 611, 'Golfito': 607, 'Grecia': 203, 'Guatuso': 215, 'Guácimo': 706, 'Heredia': 401, 'Hojancha': 511, 'Jiménez': 304, 'La Cruz': 510, 'La Unión': 303, 'León Cortés Castro': 120, 'Liberia': 501, 'Limón': 701, 'Los Chiles': 214, 'Matina': 705, 'Montes de Oro': 604, 'Mora': 107, 'Nandayure': 509, 'Naranjo': 206, 'Nicoya': 502, 'Oreamuno': 307, 'Orotina': 209, 'Osa': 605, 'Paraíso': 302, 'Parrita': 609, 'Pococí': 702, 'Puntarenas': 601, 'Puriscal': 104, 'Pérez Zeledón': 119, 'Quepos': 606, 'Río Cuarto': 216, 'San Carlos': 210, 'San Mateo': 204, 'San Pablo': 409, 'San Ramón': 202,     'Santa Ana': 109, 'Santa Cruz': 503, 'Sarapiquí': 410, 'Sarchí': 212, 'Siquirres': 703, 'Talamanca': 704, 'Tarrazú': 105, 'Tilarán': 508, 'Turrialba': 305, 'Turrubares': 116, 'Upala': 213, 'Vázquez de Coronado': 111, 'Zarcero': 211})

In [10]:
temp_max["canton"].unique()

array([507, 112, 201, 110, 306, 106, 205, 504, 402, 603, 505, 301, 506,
       610, 608, 117, 308, 602, 611, 607, 203, 215, 706, 401, 511, 304,
       510, 303, 120, 501, 701, 214, 705, 604, 107, 509, 206, 502, 307,
       209, 605, 302, 609, 702, 601, 104, 119, 606, 216, 210, 204, 409,
       202, 109, 503, 410, 212, 703, 704, 105, 508, 305, 116, 213, 111,
       211], dtype=object)

In [11]:
precip.head()

,Unnamed: 0,canton,precip_total,precip_min,precip_max,precip_mean,precip_median,week
0,1,507,16.483572,0.0,8.394386,0.686816,0.0,2020-1
1,2,112,77.464812,0.0,37.667015,6.455401,0.0,2020-1
2,3,201,56.828430,0.0,32.674007,3.551777,0.0,2020-1
3,4,110,11.819548,0.0,11.819548,2.954887,0.0,2020-1
4,5,306,27.596506,0.0,27.596506,6.899127,0.0,2020-1

In [12]:
temp_min.head()

   Unnamed: 0 canton   tmin_min   tmin_max  tmin_mean  tmin_median    week
0           1    507  31.206179  34.216175  32.980368    33.278346  2020-1
1           2    112  27.300568  31.489710  28.930743    28.016085  2020-1
2           3    201  21.756056  29.411386  26.367157    27.010843  2020-1
3           4    110  23.514788  24.153862  23.886117    23.937909  2020-1
4           5    306  23.673475  24.585056  24.102187    24.075108  2020-1

In [13]:
temp_max["week-canton"] = temp_max["week"].astype(str) + "-" + temp_max["canton"].astype(str)
temp_min["week-canton"] = temp_min["week"].astype(str) + "-" + temp_min["canton"].astype(str)
precip["week-canton"] = precip["week"].astype(str) + "-" + precip["canton"].astype(str)

In [14]:
temp_max.columns

Index(['Unnamed: 0', 'canton', 'tmax_min', 'tmax_max', 'tmax_mean',
       'tmax_median', 'week', 'week-canton'],
      dtype='str')

In [15]:
temp_max.drop(columns=['Unnamed: 0', 'week', 'canton'], inplace=True)
temp_min.drop(columns=['Unnamed: 0', 'week', 'canton'], inplace=True)
precip.drop(columns=['Unnamed: 0', 'week', 'canton'], inplace=True)

In [16]:
temp_max.head()

    tmax_min   tmax_max  tmax_mean  tmax_median week-canton
0  31.206179  34.216175  32.980368    33.278346  2020-1-507
1  27.300568  31.489710  28.930743    28.016085  2020-1-112
2  21.756056  29.411386  26.367157    27.010843  2020-1-201
3  23.514788  24.153862  23.886117    23.937909  2020-1-110
4  23.673475  24.585056  24.102187    24.075108  2020-1-306

In [17]:
temp_min.head()

    tmin_min   tmin_max  tmin_mean  tmin_median week-canton
0  31.206179  34.216175  32.980368    33.278346  2020-1-507
1  27.300568  31.489710  28.930743    28.016085  2020-1-112
2  21.756056  29.411386  26.367157    27.010843  2020-1-201
3  23.514788  24.153862  23.886117    23.937909  2020-1-110
4  23.673475  24.585056  24.102187    24.075108  2020-1-306

In [18]:
precip.head()

,precip_total,precip_min,precip_max,precip_mean,precip_median,week-canton
0,16.483572,0.0,8.394386,0.686816,0.0,2020-1-507
1,77.464812,0.0,37.667015,6.455401,0.0,2020-1-112
2,56.828430,0.0,32.674007,3.551777,0.0,2020-1-201
3,11.819548,0.0,11.819548,2.954887,0.0,2020-1-110
4,27.596506,0.0,27.596506,6.899127,0.0,2020-1-306

# Join

In [19]:
print(f'Temp max shape: {temp_max.shape}, temp min shape: {temp_min.shape}')

Temp max shape: (20196, 5), temp min shape: (20196, 5)

In [20]:
temp = pd.merge(temp_max, temp_min, on='week-canton', how='outer')

In [21]:
temp.shape

(20196, 9)

In [22]:
temp.head()

,tmax_min,tmax_max,tmax_mean,tmax_median,week-canton,tmin_min,tmin_max,tmin_mean,tmin_median
0,26.380344,33.040943,29.733966,29.475617,2020-1-104,26.380344,33.040943,29.733966,29.475617
1,23.293335,29.497790,26.818812,27.263731,2020-1-105,23.293335,29.497790,26.818812,27.263731
2,25.323180,26.002405,25.682018,25.701244,2020-1-106,25.323180,26.002405,25.682018,25.701244
3,27.604164,28.397926,28.088817,28.176588,2020-1-107,27.604164,28.397926,28.088817,28.176588
4,25.913841,26.667221,26.356873,26.423215,2020-1-109,25.913841,26.667221,26.356873,26.423215

In [23]:
print(f'Temp shape: {temp.shape}, precip shape: {precip.shape}')

Temp shape: (20196, 9), precip shape: (19932, 6)

In [24]:
temp_precip = pd.merge(temp, precip, on='week-canton', how='right')

In [25]:
temp_precip.shape

(19932, 14)

In [26]:
temp_precip.head()

,tmax_min,tmax_max,tmax_mean,tmax_median,week-canton,tmin_min,tmin_max,tmin_mean,tmin_median,precip_total,precip_min,precip_max,precip_mean,precip_median
0,31.206179,34.216175,32.980368,33.278346,2020-1-507,31.206179,34.216175,32.980368,33.278346,16.483572,0.0,8.394386,0.686816,0.0
1,27.300568,31.489710,28.930743,28.016085,2020-1-112,27.300568,31.489710,28.930743,28.016085,77.464812,0.0,37.667015,6.455401,0.0
2,21.756056,29.411386,26.367157,27.010843,2020-1-201,21.756056,29.411386,26.367157,27.010843,56.828430,0.0,32.674007,3.551777,0.0
3,23.514788,24.153862,23.886117,23.937909,2020-1-110,23.514788,24.153862,23.886117,23.937909,11.819548,0.0,11.819548,2.954887,0.0
4,23.673475,24.585056,24.102187,24.075108,2020-1-306,23.673475,24.585056,24.102187,24.075108,27.596506,0.0,27.596506,6.899127,0.0

In [27]:
print(f'Cases shape: {cases.shape}, rr shape: {rr.shape}, urb shape: {urb.shape}')

Cases shape: (29256, 2), rr shape: (29256, 2), urb shape: (26076, 2)

In [28]:
rr.columns = ['relative_risk', 'week-canton']

In [29]:
cases_rr = pd.merge(cases, rr, on=['week-canton'], how='outer')

In [30]:
cases_rr.shape

(29256, 3)

In [31]:
cases_rr.head()

   casos week-canton  relative_risk
0    168    2020-1-0       1.000000
1     22    2020-1-1       0.085698
2      3  2020-1-101       0.011373
3      0  2020-1-102       0.000000
4      6  2020-1-103       0.024177

In [32]:
urb.head()

   URBANIZACION week-canton
0             1  2020-1-101
1             1  2020-1-102
2             1  2020-1-103
3             2  2020-1-104
4             2  2020-1-105

In [33]:
urb.columns = ['urb', 'week-canton']

In [34]:
demo = pd.merge(cases_rr, urb, on='week-canton', how='right')

In [35]:
demo.shape

(26076, 4)

In [36]:
demo.head()

   casos week-canton  relative_risk  urb
0      3  2020-1-101       0.011373    1
1      0  2020-1-102       0.000000    1
2      6  2020-1-103       0.024177    1
3      0  2020-1-104       0.000000    2
4      0  2020-1-105       0.000000    2

In [37]:
print(f'Demo shape: {demo.shape}, temp_precip shape: {temp_precip.shape}, expected shape: {(temp_precip.shape[0], demo.shape[1] + temp_precip.shape[1] - 1)}')

Demo shape: (26076, 4), temp_precip shape: (19932, 14), expected shape: (19932, 17)

In [38]:
df = pd.merge(demo, temp_precip, on='week-canton', how='right')

In [39]:
df.shape

(19932, 17)

In [40]:
df.head()

,casos,week-canton,relative_risk,urb,tmax_min,tmax_max,tmax_mean,tmax_median,tmin_min,tmin_max,tmin_mean,tmin_median,precip_total,precip_min,precip_max,precip_mean,precip_median
0,2,2020-1-507,0.007854,0,31.206179,34.216175,32.980368,33.278346,31.206179,34.216175,32.980368,33.278346,16.483572,0.0,8.394386,0.686816,0.0
1,0,2020-1-112,0.000000,2,27.300568,31.489710,28.930743,28.016085,27.300568,31.489710,28.930743,28.016085,77.464812,0.0,37.667015,6.455401,0.0
2,29,2020-1-201,0.128283,1,21.756056,29.411386,26.367157,27.010843,21.756056,29.411386,26.367157,27.010843,56.828430,0.0,32.674007,3.551777,0.0
3,4,2020-1-110,0.024902,1,23.514788,24.153862,23.886117,23.937909,23.514788,24.153862,23.886117,23.937909,11.819548,0.0,11.819548,2.954887,0.0
4,0,2020-1-306,0.000000,2,23.673475,24.585056,24.102187,24.075108,23.673475,24.585056,24.102187,24.075108,27.596506,0.0,27.596506,6.899127,0.0

In [42]:
df.dtypes

casos              int64
week-canton          str
relative_risk    float64
urb                int64
tmax_min         float64
tmax_max         float64
tmax_mean        float64
tmax_median      float64
tmin_min         float64
tmin_max         float64
tmin_mean        float64
tmin_median      float64
precip_total     float64
precip_min       float64
precip_max       float64
precip_mean      float64
precip_median    float64
dtype: object

In [43]:
df['urb'] = df['urb'].astype('category')

In [44]:
df.dtypes

casos               int64
week-canton           str
relative_risk     float64
urb              category
tmax_min          float64
tmax_max          float64
tmax_mean         float64
tmax_median       float64
tmin_min          float64
tmin_max          float64
tmin_mean         float64
tmin_median       float64
precip_total      float64
precip_min        float64
precip_max        float64
precip_mean       float64
precip_median     float64
dtype: object

In [ ]:
df.to_csv('../../data/clean/full_data.csv', index=False)