# Integration of variables and cases

In [1]:
import pandas as pd

In [2]:
# REGULAR
cases = pd.read_csv('../../data/clean/casos_dengue.csv')

rr = pd.read_csv('../../data/clean/relative_risk.csv')

ndvi = pd.read_csv('../../data/clean/NDVI_int.csv')
ndvi.drop(columns=["Unnamed: 0"], inplace=True)
# lst = pd.read_csv('../../data/clean/LST_int.csv')
tmax = pd.read_csv('../../data/clean/tmax_weekly.csv')
tmax.drop(columns=["Unnamed: 0"], inplace=True)

tmin = pd.read_csv('../../data/clean/tmin_weekly.csv')
tmin.drop(columns=["Unnamed: 0"], inplace=True)

sst = pd.read_csv('../../data/clean/SST_int.csv')
sst.drop(columns=["Unnamed: 0"], inplace=True)

# temp_min = pd.read_csv('../../data/clean/TNA_int.csv')

precip = pd.read_csv('../../data/clean/precip_weekly.csv')
precip.drop(columns=["Unnamed: 0"], inplace=True)

urb = pd.read_csv('../../data/clean/urbanization.csv')

In [3]:
# LAGS
cases_lags = pd.read_csv('../../data/clean/lags/casos_dengue_lags.csv')

rr_lags = pd.read_csv('../../data/clean/lags/relative_risk_lags.csv')

ndvi_lags = pd.read_csv('../../data/clean/lags/NDVI_lags.csv')
ndvi_lags.drop(columns=["Unnamed: 0"], inplace=True)

# lst_lags = pd.read_csv('../../data/clean/LST_int.csv')

tmax_lags = pd.read_csv('../../data/clean/lags/tmax_lags.csv')
tmax_lags.drop(columns=["Unnamed: 0"], inplace=True)

tmin_lags = pd.read_csv('../../data/clean/lags/tmin_lags.csv')
tmin_lags.drop(columns=["Unnamed: 0"], inplace=True)

sst_lags = pd.read_csv('../../data/clean/lags/sst_lags.csv')
sst_lags.drop(columns=["Unnamed: 0"], inplace=True)

# temp_min = pd.read_csv('../../data/clean/TNA_int.csv')

precip_lags = pd.read_csv('../../data/clean/lags/precip_lags.csv')
precip_lags.drop(columns=["Unnamed: 0"], inplace=True)

In [4]:
cases.rename(columns = {"week-canton": "week_canton"}, inplace=True)

In [5]:
cases.head()

   casos week_canton
0    168    2020-1-0
1    171    2020-2-0
2    160    2020-3-0
3    154    2020-4-0
4    179    2020-5-0

In [6]:
no_total = ~cases['week_canton'].str.endswith("-0")
cases = cases[no_total]
no_total = ~cases['week_canton'].str.endswith("-1")
cases = cases[no_total]
no_total = ~cases['week_canton'].str.endswith("-2")
cases = cases[no_total]
no_total = ~cases['week_canton'].str.endswith("-3")
cases = cases[no_total]
no_total = ~cases['week_canton'].str.endswith("-4")
cases = cases[no_total]
no_total = ~cases['week_canton'].str.endswith("-5")
cases = cases[no_total]
no_total = ~cases['week_canton'].str.endswith("-6")
cases = cases[no_total]
no_total = ~cases['week_canton'].str.endswith("-7")
cases = cases[no_total]
no_total = ~cases['week_canton'].str.endswith("-99")
cases = cases[no_total]
no_total = ~cases['week_canton'].str.endswith("-98")
cases = cases[no_total]

In [7]:
no_total = ~cases['week_canton'].str.startswith("2020-53")
cases = cases[no_total]
no_total = ~cases['week_canton'].str.startswith("2021-53")
cases = cases[no_total]
no_total = ~cases['week_canton'].str.startswith("2022-53")
cases = cases[no_total]
no_total = ~cases['week_canton'].str.startswith("2023-53")
cases = cases[no_total]
no_total = ~cases['week_canton'].str.startswith("2024-53")
cases = cases[no_total]
no_total = ~cases['week_canton'].str.startswith("2025-53")
cases = cases[no_total]

In [8]:
cases.isna().sum()

casos          0
week_canton    0
dtype: int64

In [9]:
rr.rename(columns = {"week-canton": "week_canton"}, inplace=True)

In [10]:
rr.head()

         rr week_canton clasi_rr
0  0.258311  2020-1-101    Medio
1  0.930583  2020-2-101     Alto
2  1.356304  2020-3-101     Alto
3  0.657643  2020-4-101     Alto
4  0.000000  2020-5-101     Bajo

In [11]:
rr.isna().sum()

rr             0
week_canton    0
clasi_rr       0
dtype: int64

In [12]:
tmax.head()

    tmax_min   tmax_max  tmax_mean  tmax_median week_canton
0  33.185726  33.849937  33.578913    33.594887  2020-1-507
1  32.513170  34.540176  33.366886    33.401290  2020-2-507
2  33.072105  33.949535  33.510193    33.504290  2020-3-507
3  31.003283  34.612570  33.203586    33.105980  2020-4-507
4  32.015717  35.236813  33.583772    33.366310  2020-5-507

In [13]:
tmax.isna().sum()

tmax_min       0
tmax_max       0
tmax_mean      0
tmax_median    0
week_canton    0
dtype: int64

In [14]:
semanas_nan_tmax = tmax[tmax.isna().any(axis=1)]["week_canton"]
semanas_nan_tmax[~semanas_nan_tmax.str.endswith("-607")]

Series([], Name: week_canton, dtype: str)

In [15]:
print(709 - 405)
print(304 - 52*5) # No hay datos de tmax para Golfito ni para las semanas 40-44 del 2025

304
44

In [16]:
tmax.dropna(inplace=True)

In [17]:
tmax[tmax['week_canton'] == '2024-1-101']

        tmax_min   tmax_max  tmax_mean  tmax_median week_canton
18208  25.353212  26.950937  26.389228    26.796812  2024-1-101

In [18]:
tmin.head()

    tmin_min   tmin_max  tmin_mean  tmin_median week_canton
0  24.307365  26.021297  24.814801    24.504314  2020-1-507
1  25.027298  26.263813  25.734802    26.032413  2020-2-507
2  24.560833  27.128162  26.134207    26.378845  2020-3-507
3  22.481255  26.597519  24.225476    23.754265  2020-4-507
4  22.364380  26.545990  24.872407    25.143303  2020-5-507

In [19]:
tmin.isna().sum()

tmin_min       0
tmin_max       0
tmin_mean      0
tmin_median    0
week_canton    0
dtype: int64

In [20]:
semanas_nan_tmin = tmin[tmin.isna().any(axis=1)]["week_canton"]
semanas_nan_tmin[~semanas_nan_tmin.str.endswith("-607")]

Series([], Name: week_canton, dtype: str)

In [21]:
tmin.dropna(inplace=True) # No hay datos para Golfito ni para las semanas 40-52 del 2025

In [22]:
precip.head()

,precip_total,precip_min,precip_max,precip_mean,precip_median,week_canton
0,3.039511,0.0,3.039511,0.607902,0.0,2020-1-507
1,0.000000,0.0,0.000000,0.000000,0.0,2020-2-507
2,0.000000,0.0,0.000000,0.000000,0.0,2020-3-507
3,0.899132,0.0,0.599422,0.128447,0.0,2020-4-507
4,1.259273,0.0,1.259273,0.179896,0.0,2020-5-507

In [23]:
precip.isna().sum()

precip_total     0
precip_min       0
precip_max       0
precip_mean      0
precip_median    0
week_canton      0
dtype: int64

In [24]:
semanas_nan_precip = precip[precip.isna().any(axis=1)]["week_canton"]
semanas_nan_precip[~semanas_nan_precip.str.endswith("-607")]

Series([], Name: week_canton, dtype: str)

In [25]:
precip[precip["week_canton"].str.startswith("2025-40")]

,precip_total,precip_min,precip_max,precip_mean,precip_median,week_canton
299,36.101292,18.050646,18.050646,18.050646,18.050646,2025-40-507
599,40.630997,0.000000,40.630997,20.315499,20.315499,2025-40-112
899,33.246438,16.623219,16.623219,16.623219,16.623219,2025-40-201
1199,33.480360,11.160120,22.320240,16.740180,16.740180,2025-40-110
1499,23.551695,7.850565,15.701130,11.775847,11.775847,2025-40-306
...,...,...,...,...,...,...
23099,33.105145,0.000000,33.105145,16.552573,16.552573,2025-40-305
23399,11.547569,0.000000,11.547569,5.773784,5.773784,2025-40-116
23699,36.906696,12.302232,24.604464,18.453348,18.453348,2025-40-213
23999,36.152112,12.050704,24.101408,18.076056,18.076056,2025-40-111
24299,22.935444,0.000000,22.935444,11.467722,11.467722,2025-40-211

In [26]:
precip.dropna(inplace=True) # No hay datos para Golfito ni para las semanas 41-52 del 2025

In [27]:
ndvi.head()

  week_canton    ndvi
0  2020-1-201  0.8913
1  2020-1-205  0.7437
2  2020-1-203  0.7113
3  2020-1-215  0.7439
4  2020-1-214  0.7885

In [28]:
ndvi.isna().sum()

week_canton    0
ndvi           0
dtype: int64

In [29]:
#lst.drop(columns=["Unnamed: 0"], inplace=True)
#lst.head()

In [30]:
sst.head()

  week_canton  nino34ssta
0  2020-1-101    0.535371
1  2020-1-102    0.535371
2  2020-1-103    0.535371
3  2020-1-104    0.535371
4  2020-1-105    0.535371

In [31]:
sst.isna().sum()

week_canton    0
nino34ssta     0
dtype: int64

In [32]:
urb.head()

   urb week_canton
0    1  2020-1-101
1    1  2020-1-102
2    1  2020-1-103
3    2  2020-1-104
4    2  2020-1-105

In [33]:
urb.isna().sum()

urb            0
week_canton    0
dtype: int64

In [34]:
urb[urb["week_canton"].str.contains("-53")]

       urb  week_canton
4264     1  2020-53-101
4265     1  2020-53-102
4266     1  2020-53-103
4267     2  2020-53-104
4268     2  2020-53-105
...    ...          ...
26071    0  2025-53-702
26072    0  2025-53-703
26073    0  2025-53-704
26074    0  2025-53-705
26075    2  2025-53-706

[492 rows x 2 columns]

In [35]:
no_total = ~urb['week_canton'].str.contains("-53")
urb = urb[no_total]
no_total = ~urb['week_canton'].str.contains("-53")
urb = urb[no_total]
no_total = ~urb['week_canton'].str.contains("-53")
urb = urb[no_total]
no_total = ~urb['week_canton'].str.contains("-53")
urb = urb[no_total]
no_total = ~urb['week_canton'].str.contains("-53")
urb = urb[no_total]
no_total = ~urb['week_canton'].str.contains("-53")
urb = urb[no_total]
no_total = ~urb['week_canton'].str.contains("-53")
urb = urb[no_total]
no_total = ~urb['week_canton'].str.contains("-53")
urb = urb[no_total]
no_total = ~urb['week_canton'].str.contains("-53")
urb = urb[no_total]
no_total = ~urb['week_canton'].str.contains("-53")
urb = urb[no_total]

In [36]:
urb.shape

(25584, 2)

In [37]:
# Dimensions

print(f"""
      cases: {cases.shape}
      rr: {rr.shape}
      ndvi: {ndvi.shape}
      tmax: {tmax.shape}
      tmin: {tmin.shape}
      sst: {sst.shape}
      precip: {precip.shape}
      urb: {urb.shape}
      """)

      cases: (25584, 2)
      rr: (25584, 3)
      ndvi: (25272, 2)
      tmax: (24300, 5)
      tmin: (24300, 5)
      sst: (25584, 2)
      precip: (24300, 6)
      urb: (25584, 2)

# Lags

In [38]:
cases_lags.isna().sum()

Unnamed: 0     0
week_canton    0
casos_lag_8    0
casos_lag_7    0
casos_lag_6    0
casos_lag_5    0
casos_lag_4    0
casos_lag_3    0
casos_lag_2    0
casos_lag_1    0
dtype: int64

In [39]:
rr_lags.isna().sum()

Unnamed: 0        0
week_canton       0
rr_lag_8          0
rr_lag_7          0
rr_lag_6          0
rr_lag_5          0
rr_lag_4          0
rr_lag_3          0
rr_lag_2          0
rr_lag_1          0
clasi_rr_lag_8    0
clasi_rr_lag_7    0
clasi_rr_lag_6    0
clasi_rr_lag_5    0
clasi_rr_lag_4    0
clasi_rr_lag_3    0
clasi_rr_lag_2    0
clasi_rr_lag_1    0
dtype: int64

In [40]:
ndvi_lags.isna().sum()

week_canton    0
ndvi_lag_8     0
ndvi_lag_7     0
ndvi_lag_6     0
ndvi_lag_5     0
ndvi_lag_4     0
ndvi_lag_3     0
ndvi_lag_2     0
ndvi_lag_1     0
dtype: int64

In [41]:
tmax_lags.isna().sum()

week_canton          0
tmax_max_lag_8       0
tmax_max_lag_7       0
tmax_max_lag_6       0
tmax_max_lag_5       0
tmax_max_lag_4       0
tmax_max_lag_3       0
tmax_max_lag_2       0
tmax_max_lag_1       0
tmax_mean_lag_8      0
tmax_mean_lag_7      0
tmax_mean_lag_6      0
tmax_mean_lag_5      0
tmax_mean_lag_4      0
tmax_mean_lag_3      0
tmax_mean_lag_2      0
tmax_mean_lag_1      0
tmax_median_lag_8    0
tmax_median_lag_7    0
tmax_median_lag_6    0
tmax_median_lag_5    0
tmax_median_lag_4    0
tmax_median_lag_3    0
tmax_median_lag_2    0
tmax_median_lag_1    0
tmax_min_lag_8       0
tmax_min_lag_7       0
tmax_min_lag_6       0
tmax_min_lag_5       0
tmax_min_lag_4       0
tmax_min_lag_3       0
tmax_min_lag_2       0
tmax_min_lag_1       0
dtype: int64

In [42]:
semanas_nan_tmax_lags = tmax_lags[tmax_lags.isna().any(axis=1)]["week_canton"]
semanas_nan_tmax_lags[~semanas_nan_tmax_lags.str.endswith("-607")]

Series([], Name: week_canton, dtype: str)

In [43]:
precip_lags.isna().sum()

week_canton            0
precip_total_lag_8     0
precip_total_lag_7     0
precip_total_lag_6     0
precip_total_lag_5     0
precip_total_lag_4     0
precip_total_lag_3     0
precip_total_lag_2     0
precip_total_lag_1     0
precip_max_lag_8       0
precip_max_lag_7       0
precip_max_lag_6       0
precip_max_lag_5       0
precip_max_lag_4       0
precip_max_lag_3       0
precip_max_lag_2       0
precip_max_lag_1       0
precip_mean_lag_8      0
precip_mean_lag_7      0
precip_mean_lag_6      0
precip_mean_lag_5      0
precip_mean_lag_4      0
precip_mean_lag_3      0
precip_mean_lag_2      0
precip_mean_lag_1      0
precip_median_lag_8    0
precip_median_lag_7    0
precip_median_lag_6    0
precip_median_lag_5    0
precip_median_lag_4    0
precip_median_lag_3    0
precip_median_lag_2    0
precip_median_lag_1    0
precip_min_lag_8       0
precip_min_lag_7       0
precip_min_lag_6       0
precip_min_lag_5       0
precip_min_lag_4       0
precip_min_lag_3       0
precip_min_lag_2       0
precip_min_lag_1       0
dtype: int64

In [44]:
tmin_lags.isna().sum()

week_canton          0
tmin_max_lag_8       0
tmin_max_lag_7       0
tmin_max_lag_6       0
tmin_max_lag_5       0
tmin_max_lag_4       0
tmin_max_lag_3       0
tmin_max_lag_2       0
tmin_max_lag_1       0
tmin_mean_lag_8      0
tmin_mean_lag_7      0
tmin_mean_lag_6      0
tmin_mean_lag_5      0
tmin_mean_lag_4      0
tmin_mean_lag_3      0
tmin_mean_lag_2      0
tmin_mean_lag_1      0
tmin_median_lag_8    0
tmin_median_lag_7    0
tmin_median_lag_6    0
tmin_median_lag_5    0
tmin_median_lag_4    0
tmin_median_lag_3    0
tmin_median_lag_2    0
tmin_median_lag_1    0
tmin_min_lag_8       0
tmin_min_lag_7       0
tmin_min_lag_6       0
tmin_min_lag_5       0
tmin_min_lag_4       0
tmin_min_lag_3       0
tmin_min_lag_2       0
tmin_min_lag_1       0
dtype: int64

In [45]:
sst_lags.isna().sum()

week_canton         0
nino34ssta_lag_8    0
nino34ssta_lag_7    0
nino34ssta_lag_6    0
nino34ssta_lag_5    0
nino34ssta_lag_4    0
nino34ssta_lag_3    0
nino34ssta_lag_2    0
nino34ssta_lag_1    0
dtype: int64

# Join

In [46]:
print(f'Temp max shape: {tmax.shape}, temp min shape: {tmin.shape}')

Temp max shape: (24300, 5), temp min shape: (24300, 5)

In [47]:
temp = pd.merge(tmin, tmax, on='week_canton', how='inner')

In [48]:
temp.shape

(24300, 9)

In [49]:
temp.head()

,tmin_min,tmin_max,tmin_mean,tmin_median,week_canton,tmax_min,tmax_max,tmax_mean,tmax_median
0,24.307365,26.021297,24.814801,24.504314,2020-1-507,33.185726,33.849937,33.578913,33.594887
1,25.027298,26.263813,25.734802,26.032413,2020-2-507,32.513170,34.540176,33.366886,33.401290
2,24.560833,27.128162,26.134207,26.378845,2020-3-507,33.072105,33.949535,33.510193,33.504290
3,22.481255,26.597519,24.225476,23.754265,2020-4-507,31.003283,34.612570,33.203586,33.105980
4,22.364380,26.545990,24.872407,25.143303,2020-5-507,32.015717,35.236813,33.583772,33.366310

In [50]:
print(f'Temp shape: {temp.shape}, precip shape: {precip.shape}')

Temp shape: (24300, 9), precip shape: (24300, 6)

In [51]:
temp_precip = pd.merge(temp, precip, on='week_canton', how='inner')

In [52]:
temp_precip.shape

(24300, 14)

In [53]:
temp_precip.head()

,tmin_min,tmin_max,tmin_mean,tmin_median,week_canton,tmax_min,tmax_max,tmax_mean,tmax_median,precip_total,precip_min,precip_max,precip_mean,precip_median
0,24.307365,26.021297,24.814801,24.504314,2020-1-507,33.185726,33.849937,33.578913,33.594887,3.039511,0.0,3.039511,0.607902,0.0
1,25.027298,26.263813,25.734802,26.032413,2020-2-507,32.513170,34.540176,33.366886,33.401290,0.000000,0.0,0.000000,0.000000,0.0
2,24.560833,27.128162,26.134207,26.378845,2020-3-507,33.072105,33.949535,33.510193,33.504290,0.000000,0.0,0.000000,0.000000,0.0
3,22.481255,26.597519,24.225476,23.754265,2020-4-507,31.003283,34.612570,33.203586,33.105980,0.899132,0.0,0.599422,0.128447,0.0
4,22.364380,26.545990,24.872407,25.143303,2020-5-507,32.015717,35.236813,33.583772,33.366310,1.259273,0.0,1.259273,0.179896,0.0

In [54]:
print(f'Cases shape: {cases.shape}, rr shape: {rr.shape}, urb shape: {urb.shape}')

Cases shape: (25584, 2), rr shape: (25584, 3), urb shape: (25584, 2)

In [55]:
cases_rr = pd.merge(cases, rr, on=['week_canton'], how='inner')

In [56]:
cases_rr.shape

(25584, 4)

In [57]:
cases_rr.head()

   casos week_canton        rr clasi_rr
0      3  2020-1-101  0.258311    Medio
1     11  2020-2-101  0.930583     Alto
2     15  2020-3-101  1.356304     Alto
3      7  2020-4-101  0.657643     Alto
4      0  2020-5-101  0.000000     Bajo

In [58]:
urb.head()

   urb week_canton
0    1  2020-1-101
1    1  2020-1-102
2    1  2020-1-103
3    2  2020-1-104
4    2  2020-1-105

In [59]:
demo = pd.merge(cases_rr, urb, on='week_canton', how='inner')

In [60]:
demo.shape

(25584, 5)

In [61]:
demo.head()

   casos week_canton        rr clasi_rr  urb
0      3  2020-1-101  0.258311    Medio    1
1     11  2020-2-101  0.930583     Alto    1
2     15  2020-3-101  1.356304     Alto    1
3      7  2020-4-101  0.657643     Alto    1
4      0  2020-5-101  0.000000     Bajo    1

In [62]:
print(f'Demo shape: {demo.shape}, temp_precip shape: {temp_precip.shape}, expected shape: {(temp_precip.shape[0], demo.shape[1] + temp_precip.shape[1] - 1)}')

Demo shape: (25584, 5), temp_precip shape: (24300, 14), expected shape: (24300, 18)

In [63]:
demo_temp_precip = pd.merge(demo, temp_precip, on='week_canton', how='inner')

In [64]:
demo_temp_precip.shape

(24300, 18)

In [65]:
sst_ndvi = pd.merge(sst, ndvi, on='week_canton', how='inner')

In [66]:
demo_temp_precip[demo_temp_precip['week_canton'] == "2025-41-101"]

Empty DataFrame
Columns: [casos, week_canton, rr, clasi_rr, urb, tmin_min, tmin_max, tmin_mean, tmin_median, tmax_min, tmax_max, tmax_mean, tmax_median, precip_total, precip_min, precip_max, precip_mean, precip_median]
Index: []

In [67]:
sst_ndvi.shape

(25272, 3)

In [68]:
df_no_lag = pd.merge(demo_temp_precip, sst_ndvi, on='week_canton', how='inner')

In [69]:
df_no_lag.shape

(24300, 20)

In [70]:
df_lag1 = pd.merge(df_no_lag, cases_lags, on='week_canton', how='inner')

In [71]:
df_lag1.shape

(23652, 29)

In [72]:
df_lag2 = pd.merge(df_lag1, rr_lags, on='week_canton', how='inner')
df_lag3 = pd.merge(df_lag2, ndvi_lags, on='week_canton', how='inner')
df_lag4 = pd.merge(df_lag3, tmax_lags, on='week_canton', how='inner')
df_lag5 = pd.merge(df_lag4, tmin_lags, on='week_canton', how='inner')
df_lag6 = pd.merge(df_lag5, sst_lags, on='week_canton', how='inner')
df = pd.merge(df_lag6, precip_lags, on='week_canton', how='inner')

In [73]:
df.shape

(23652, 166)

In [74]:
df.head()

,casos,week_canton,rr,clasi_rr,urb,tmin_min,tmin_max,tmin_mean,tmin_median,tmax_min,...,precip_median_lag_2,precip_median_lag_1,precip_min_lag_8,precip_min_lag_7,precip_min_lag_6,precip_min_lag_5,precip_min_lag_4,precip_min_lag_3,precip_min_lag_2,precip_min_lag_1
0,4,2020-9-101,0.459451,Medio,1,16.785858,20.006693,18.775265,19.645410,26.733393,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2,2020-10-101,0.224397,Medio,1,17.235245,19.964815,18.723231,18.793407,26.638765,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2,2020-11-101,0.253939,Medio,1,18.474545,19.621017,19.110772,19.157510,27.162430,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0,2020-12-101,0.000000,Bajo,1,18.497475,19.358017,18.967383,19.099348,26.924604,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0,2020-13-101,0.000000,Bajo,1,17.836336,19.390366,18.653528,18.680185,27.018480,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [75]:
df.dtypes

casos                 int64
week_canton             str
rr                  float64
clasi_rr                str
urb                   int64
                     ...
precip_min_lag_5    float64
precip_min_lag_4    float64
precip_min_lag_3    float64
precip_min_lag_2    float64
precip_min_lag_1    float64
Length: 166, dtype: object

In [76]:
df['urb'] = df['urb'].astype('category')
df['clasi_rr'] = df['clasi_rr'].astype('category')
df['clasi_rr_lag_1'] = df['clasi_rr_lag_1'].astype('category')
df['clasi_rr_lag_2'] = df['clasi_rr_lag_2'].astype('category')
df['clasi_rr_lag_3'] = df['clasi_rr_lag_3'].astype('category')
df['clasi_rr_lag_4'] = df['clasi_rr_lag_4'].astype('category')
df['clasi_rr_lag_5'] = df['clasi_rr_lag_5'].astype('category')
df['clasi_rr_lag_6'] = df['clasi_rr_lag_6'].astype('category')
df['clasi_rr_lag_7'] = df['clasi_rr_lag_7'].astype('category')
df['clasi_rr_lag_8'] = df['clasi_rr_lag_8'].astype('category')

In [77]:
df.dtypes

casos                  int64
week_canton              str
rr                   float64
clasi_rr            category
urb                 category
                      ...
precip_min_lag_5     float64
precip_min_lag_4     float64
precip_min_lag_3     float64
precip_min_lag_2     float64
precip_min_lag_1     float64
Length: 166, dtype: object

In [78]:
df.to_csv('../../data/clean/full_data.csv', index=False)