# Integration of variables and cases

In [1]:
import pandas as pd

In [25]:
# REGULAR
cases = pd.read_csv('../../data/clean/casos_dengue.csv')

rr = pd.read_csv('../../data/clean/relative_risk.csv')

ndvi = pd.read_csv('../../data/clean/NDVI_int.csv')
ndvi.drop(columns=["Unnamed: 0"], inplace=True)
# lst = pd.read_csv('../../data/clean/LST_int.csv')
tmax = pd.read_csv('../../data/clean/tmax_weekly.csv')
tmax.drop(columns=["Unnamed: 0"], inplace=True)

tmin = pd.read_csv('../../data/clean/tmin_weekly.csv')
tmin.drop(columns=["Unnamed: 0"], inplace=True)

sst = pd.read_csv('../../data/clean/SST_int.csv')
sst.drop(columns=["Unnamed: 0"], inplace=True)

# temp_min = pd.read_csv('../../data/clean/TNA_int.csv')

precip = pd.read_csv('../../data/clean/precip_weekly.csv')
precip.drop(columns=["Unnamed: 0"], inplace=True)

urb = pd.read_csv('../../data/clean/urbanization.csv')

In [3]:
# LAGS
cases_lags = pd.read_csv('../../data/clean/lags/casos_dengue_lags.csv')

rr_lags = pd.read_csv('../../data/clean/lags/relative_risk_lags.csv')

ndvi_lags = pd.read_csv('../../data/clean/lags/NDVI_lags.csv')
ndvi_lags.drop(columns=["Unnamed: 0"], inplace=True)

# lst_lags = pd.read_csv('../../data/clean/LST_int.csv')

tmax_lags = pd.read_csv('../../data/clean/lags/tmax_lags.csv')
tmax_lags.drop(columns=["Unnamed: 0"], inplace=True)

tmin_lags = pd.read_csv('../../data/clean/lags/tmin_lags.csv')
tmin_lags.drop(columns=["Unnamed: 0"], inplace=True)

sst_lags = pd.read_csv('../../data/clean/lags/sst_lags.csv')
sst_lags.drop(columns=["Unnamed: 0"], inplace=True)

# temp_min = pd.read_csv('../../data/clean/TNA_int.csv')

precip_lags = pd.read_csv('../../data/clean/lags/precip_lags.csv')
precip_lags.drop(columns=["Unnamed: 0"], inplace=True)

In [29]:
cases.rename(columns = {"week-canton": "week_canton"}, inplace=True)

In [30]:
cases.head()

   casos week_canton
0    168    2020-1-0
1    171    2020-2-0
2    160    2020-3-0
3    154    2020-4-0
4    179    2020-5-0

In [32]:
no_total = ~cases['week_canton'].str.endswith("-0")
cases = cases[no_total]
no_total = ~cases['week_canton'].str.endswith("-1")
cases = cases[no_total]
no_total = ~cases['week_canton'].str.endswith("-2")
cases = cases[no_total]
no_total = ~cases['week_canton'].str.endswith("-3")
cases = cases[no_total]
no_total = ~cases['week_canton'].str.endswith("-4")
cases = cases[no_total]
no_total = ~cases['week_canton'].str.endswith("-5")
cases = cases[no_total]
no_total = ~cases['week_canton'].str.endswith("-6")
cases = cases[no_total]
no_total = ~cases['week_canton'].str.endswith("-7")
cases = cases[no_total]
no_total = ~cases['week_canton'].str.endswith("-99")
cases = cases[no_total]
no_total = ~cases['week_canton'].str.endswith("-98")
cases = cases[no_total]

In [33]:
no_total = ~cases['week_canton'].str.startswith("2020-53")
cases = cases[no_total]
no_total = ~cases['week_canton'].str.startswith("2021-53")
cases = cases[no_total]
no_total = ~cases['week_canton'].str.startswith("2022-53")
cases = cases[no_total]
no_total = ~cases['week_canton'].str.startswith("2023-53")
cases = cases[no_total]
no_total = ~cases['week_canton'].str.startswith("2024-53")
cases = cases[no_total]
no_total = ~cases['week_canton'].str.startswith("2025-53")
cases = cases[no_total]

In [34]:
rr.rename(columns = {"week-canton": "week_canton"}, inplace=True)

In [35]:
rr.head()

         rr week_canton clasi_rr
0  0.258311  2020-1-101    Medio
1  0.930583  2020-2-101     Alto
2  1.356304  2020-3-101     Alto
3  0.657643  2020-4-101     Alto
4  0.000000  2020-5-101     Bajo

In [8]:
tmax.head()

    tmax_min   tmax_max  tmax_mean  tmax_median week_canton
0  33.185726  33.849937  33.578913    33.594887  2020-1-507
1  26.316240  27.293066  26.838383    26.761051  2020-1-112
2  25.749187  26.673803  26.204433    26.218884  2020-1-201
3  23.514788  24.153862  23.878840    23.849730  2020-1-110
4  21.239576  22.188282  21.588210    21.481771  2020-1-306

In [9]:
tmin.head()

    tmin_min   tmin_max  tmin_mean  tmin_median week_canton
0  24.307365  26.021297  24.814801    24.504314  2020-1-507
1  19.743813  20.537115  20.030698    19.975498  2020-1-112
2  17.587805  19.524090  18.199087    17.867570  2020-1-201
3  15.657812  16.869596  16.108704    15.963184  2020-1-110
4  13.576344  14.808821  14.152639    14.069752  2020-1-306

In [10]:
precip.head()

,precip_total,precip_min,precip_max,precip_mean,precip_median,week_canton
0,3.039511,0.0,3.039511,0.607902,0.0,2020-1-507
1,46.348244,0.0,46.348244,9.269649,0.0,2020-1-112
2,5.230224,0.0,3.922668,1.046045,0.0,2020-1-201
3,11.819548,0.0,11.819548,2.363910,0.0,2020-1-110
4,27.190937,0.0,27.190937,5.438187,0.0,2020-1-306

In [11]:
ndvi.head()

  week_canton    ndvi
0  2020-1-201  0.8913
1  2020-1-205  0.7437
2  2020-1-203  0.7113
3  2020-1-215  0.7439
4  2020-1-214  0.7885

In [12]:
#lst.drop(columns=["Unnamed: 0"], inplace=True)
#lst.head()

In [13]:
sst.head()

  week_canton  nino34ssta
0  2020-1-101    0.535371
1  2020-1-102    0.535371
2  2020-1-103    0.535371
3  2020-1-104    0.535371
4  2020-1-105    0.535371

In [14]:
urb.head()

   urb week_canton
0    1  2020-1-101
1    1  2020-1-102
2    1  2020-1-103
3    2  2020-1-104
4    2  2020-1-105

In [15]:
# Dimensions

print(f"""
      cases: {cases.shape}
      rr: {rr.shape}
      ndvi: {ndvi.shape}
      tmax: {tmax.shape}
      tmin: {tmin.shape}
      sst: {sst.shape}
      precip: {precip.shape}
      urb: {urb.shape}
      """)

      cases: (25584, 2)
      rr: (25584, 3)
      ndvi: (25272, 2)
      tmax: (24928, 5)
      tmin: (24600, 5)
      sst: (25584, 2)
      precip: (24682, 6)
      urb: (26076, 2)

# Join

In [36]:
print(f'Temp max shape: {tmax.shape}, temp min shape: {tmin.shape}')

Temp max shape: (24928, 5), temp min shape: (24600, 5)

In [40]:
temp = pd.merge(tmin, tmax, on='week_canton', how='inner')

In [41]:
temp.shape

(24600, 9)

In [42]:
temp.head()

,tmin_min,tmin_max,tmin_mean,tmin_median,week_canton,tmax_min,tmax_max,tmax_mean,tmax_median
0,24.307365,26.021297,24.814801,24.504314,2020-1-507,33.185726,33.849937,33.578913,33.594887
1,19.743813,20.537115,20.030698,19.975498,2020-1-112,26.316240,27.293066,26.838383,26.761051
2,17.587805,19.524090,18.199087,17.867570,2020-1-201,25.749187,26.673803,26.204433,26.218884
3,15.657812,16.869596,16.108704,15.963184,2020-1-110,23.514788,24.153862,23.878840,23.849730
4,13.576344,14.808821,14.152639,14.069752,2020-1-306,21.239576,22.188282,21.588210,21.481771

In [43]:
print(f'Temp shape: {temp.shape}, precip shape: {precip.shape}')

Temp shape: (24600, 9), precip shape: (24682, 6)

In [46]:
temp_precip = pd.merge(temp, precip, on='week_canton', how='inner')

In [47]:
temp_precip.shape

(24600, 14)

In [48]:
temp_precip.head()

,tmin_min,tmin_max,tmin_mean,tmin_median,week_canton,tmax_min,tmax_max,tmax_mean,tmax_median,precip_total,precip_min,precip_max,precip_mean,precip_median
0,24.307365,26.021297,24.814801,24.504314,2020-1-507,33.185726,33.849937,33.578913,33.594887,3.039511,0.0,3.039511,0.607902,0.0
1,19.743813,20.537115,20.030698,19.975498,2020-1-112,26.316240,27.293066,26.838383,26.761051,46.348244,0.0,46.348244,9.269649,0.0
2,17.587805,19.524090,18.199087,17.867570,2020-1-201,25.749187,26.673803,26.204433,26.218884,5.230224,0.0,3.922668,1.046045,0.0
3,15.657812,16.869596,16.108704,15.963184,2020-1-110,23.514788,24.153862,23.878840,23.849730,11.819548,0.0,11.819548,2.363910,0.0
4,13.576344,14.808821,14.152639,14.069752,2020-1-306,21.239576,22.188282,21.588210,21.481771,27.190937,0.0,27.190937,5.438187,0.0

In [49]:
print(f'Cases shape: {cases.shape}, rr shape: {rr.shape}, urb shape: {urb.shape}')

Cases shape: (25584, 2), rr shape: (25584, 3), urb shape: (26076, 2)

In [50]:
cases_rr = pd.merge(cases, rr, on=['week_canton'], how='inner')

In [51]:
cases_rr.shape

(25584, 4)

In [52]:
cases_rr.head()

   casos week_canton        rr clasi_rr
0      3  2020-1-101  0.258311    Medio
1     11  2020-2-101  0.930583     Alto
2     15  2020-3-101  1.356304     Alto
3      7  2020-4-101  0.657643     Alto
4      0  2020-5-101  0.000000     Bajo

In [53]:
urb.head()

   urb week_canton
0    1  2020-1-101
1    1  2020-1-102
2    1  2020-1-103
3    2  2020-1-104
4    2  2020-1-105

In [54]:
demo = pd.merge(cases_rr, urb, on='week_canton', how='inner')

In [55]:
demo.shape

(25584, 5)

In [56]:
demo.head()

   casos week_canton        rr clasi_rr  urb
0      3  2020-1-101  0.258311    Medio    1
1     11  2020-2-101  0.930583     Alto    1
2     15  2020-3-101  1.356304     Alto    1
3      7  2020-4-101  0.657643     Alto    1
4      0  2020-5-101  0.000000     Bajo    1

In [57]:
print(f'Demo shape: {demo.shape}, temp_precip shape: {temp_precip.shape}, expected shape: {(temp_precip.shape[0], demo.shape[1] + temp_precip.shape[1] - 1)}')

Demo shape: (25584, 5), temp_precip shape: (24600, 14), expected shape: (24600, 18)

In [62]:
demo_temp_precip = pd.merge(demo, temp_precip, on='week_canton', how='inner')

In [ ]:
demo_temp_precip.shape

(24600, 18)

In [63]:
sst_ndvi = pd.merge(sst, ndvi, on='week_canton', how='inner')

In [71]:
demo_temp_precip[demo_temp_precip['week_canton'] == "2025-41-101"]

Empty DataFrame
Columns: [casos, week_canton, rr, clasi_rr, urb, tmin_min, tmin_max, tmin_mean, tmin_median, tmax_min, tmax_max, tmax_mean, tmax_median, precip_total, precip_min, precip_max, precip_mean, precip_median]
Index: []

In [67]:
sst_ndvi.shape

(25272, 3)

In [65]:
df_no_lag = pd.merge(demo_temp_precip, sst_ndvi, on='week_canton', how='inner')

In [66]:
df_no_lag.shape

(24300, 20)

In [74]:
df_lag1 = pd.merge(df_no_lag, cases_lags, on='week_canton', how='inner')

In [75]:
df_lag1.shape

(23652, 29)

In [86]:
df_lag2 = pd.merge(df_lag1, rr_lags, on='week_canton', how='inner')
df_lag3 = pd.merge(df_lag2, ndvi_lags, on='week_canton', how='inner')
df_lag4 = pd.merge(df_lag3, tmax_lags, on='week_canton', how='inner')
df_lag5 = pd.merge(df_lag4, tmin_lags, on='week_canton', how='inner')
df_lag6 = pd.merge(df_lag5, sst_lags, on='week_canton', how='inner')
df = pd.merge(df_lag6, precip_lags, on='week_canton', how='inner')

In [78]:
df.shape

(22761, 166)

In [79]:
df.head()

,casos,week_canton,rr,clasi_rr,urb,tmin_min,tmin_max,tmin_mean,tmin_median,tmax_min,...,precip_median_lag_2,precip_median_lag_1,precip_min_lag_8,precip_min_lag_7,precip_min_lag_6,precip_min_lag_5,precip_min_lag_4,precip_min_lag_3,precip_min_lag_2,precip_min_lag_1
0,4,2020-9-101,0.459451,Medio,1,16.785858,20.006693,18.775265,19.645410,26.733393,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
1,2,2020-10-101,0.224397,Medio,1,17.235245,19.964815,18.723231,18.793407,26.638765,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
2,2,2020-11-101,0.253939,Medio,1,18.474545,19.621017,19.110772,19.157510,27.162430,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
3,0,2020-12-101,0.000000,Bajo,1,18.497475,19.358017,18.967383,19.099348,26.924604,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.377879,0.0,0.0
4,0,2020-13-101,0.000000,Bajo,1,17.836336,19.390366,18.653528,18.680185,27.018480,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0

In [87]:
df.dtypes

casos                 int64
week_canton             str
rr                  float64
clasi_rr                str
urb                   int64
                     ...
precip_min_lag_5    float64
precip_min_lag_4    float64
precip_min_lag_3    float64
precip_min_lag_2    float64
precip_min_lag_1    float64
Length: 166, dtype: object

In [ ]:
df['urb'] = df['urb'].astype('category')
df['clasi_rr'] = df['clasi_rr'].astype('category')
df['clasi_rr_lag_1'] = df['clasi_rr_lag_1'].astype('category')
df['clasi_rr_lag_2'] = df['clasi_rr_lag_2'].astype('category')
df['clasi_rr_lag_3'] = df['clasi_rr_lag_3'].astype('category')
df['clasi_rr_lag_4'] = df['clasi_rr_lag_4'].astype('category')
df['clasi_rr_lag_5'] = df['clasi_rr_lag_5'].astype('category')
df['clasi_rr_lag_6'] = df['clasi_rr_lag_6'].astype('category')
df['clasi_rr_lag_7'] = df['clasi_rr_lag_7'].astype('category')
df['clasi_rr_lag_8'] = df['clasi_rr_lag_8'].astype('category')

In [84]:
df.dtypes

casos                  int64
week_canton              str
rr                   float64
clasi_rr            category
urb                 category
                      ...
precip_min_lag_5     float64
precip_min_lag_4     float64
precip_min_lag_3     float64
precip_min_lag_2     float64
precip_min_lag_1     float64
Length: 166, dtype: object

In [73]:
df.to_csv('../../data/clean/full_data.csv', index=False)