# <a id='toc1_'></a>[Integration of variables and cases](#toc0_)

This notebook takes the separate datasets for each variable and integrates it into a big dataset ready to feed into the models

**Table of contents**<a id='toc0_'></a>    
- [Integration of variables and cases](#toc1_)    
  - [Load datasets](#toc1_1_)    
- [Lags](#toc2_)    
- [Join](#toc3_)    

<!-- vscode-jupyter-toc-config
	numbering=false
	anchor=true
	flat=false
	minLevel=1
	maxLevel=6
	/vscode-jupyter-toc-config -->
<!-- THIS CELL WILL BE REPLACED ON TOC UPDATE. DO NOT WRITE YOUR TEXT IN THIS CELL -->

In [70]:
import pandas as pd

## <a id='toc1_1_'></a>[Load datasets](#toc0_)

In [71]:
# REGULAR
cases = pd.read_csv('../data/interim/casos_dengue.csv')

rr = pd.read_csv('../data/interim/relative_risk.csv')
rr.drop(columns=["Unnamed: 0"], inplace=True)
rr = rr.rename(columns = {"week-canton": "week_canton"})

ndvi = pd.read_csv('../data/interim/NDVI_int.csv')
ndvi.drop(columns=["Unnamed: 0"], inplace=True)

tmax = pd.read_csv('../data/interim/tmax_weekly.csv')
tmax.drop(columns=["Unnamed: 0"], inplace=True)

tmin = pd.read_csv('../data/interim/tmin_weekly.csv')
tmin.drop(columns=["Unnamed: 0"], inplace=True)

temp_prom = pd.read_csv('../data/interim/temp_prom.csv')
temp_prom.drop(columns=["Unnamed: 0"], inplace=True)

sst = pd.read_csv('../data/interim/SST_int.csv')
sst.drop(columns=["Unnamed: 0"], inplace=True)

keywords = pd.read_csv('../data/interim/trends_keywords.csv')
keywords.drop(columns=["Unnamed: 0"], inplace=True)

precip = pd.read_csv('../data/interim/precip_weekly.csv')
precip.drop(columns=["Unnamed: 0"], inplace=True)

urb = pd.read_csv('../data/interim/urbanization.csv')

In [72]:
# LAGS
cases_lags = pd.read_csv('../data/interim/lags/casos_dengue_lags.csv')
cases_lags.drop(columns=["Unnamed: 0"], inplace=True)

rr_lags = pd.read_csv('../data/interim/lags/relative_risk_lags.csv')
rr_lags.drop(columns=["Unnamed: 0"], inplace=True)

ndvi_lags = pd.read_csv('../data/interim/lags/NDVI_lags.csv')
ndvi_lags.drop(columns=["Unnamed: 0"], inplace=True)

tmax_lags = pd.read_csv('../data/interim/lags/tmax_lags.csv')
tmax_lags.drop(columns=["Unnamed: 0"], inplace=True)

tmin_lags = pd.read_csv('../data/interim/lags/tmin_lags.csv')
tmin_lags.drop(columns=["Unnamed: 0"], inplace=True)

temp_prom_lags = pd.read_csv('../data/interim/lags/temp_prom_lags.csv')
temp_prom_lags.drop(columns=["Unnamed: 0"], inplace=True)

sst_lags = pd.read_csv('../data/interim/lags/sst_lags.csv')
sst_lags.drop(columns=["Unnamed: 0"], inplace=True)

precip_lags = pd.read_csv('../data/interim/lags/precip_lags.csv')
precip_lags.drop(columns=["Unnamed: 0"], inplace=True)

keywords_lags = pd.read_csv('../data/interim/lags/trends_keywords_lags.csv')
keywords_lags.drop(columns=["Unnamed: 0"], inplace=True)

In [73]:
cases.head()

   casos week_canton
0    168    2020-1-0
1    171    2020-2-0
2    160    2020-3-0
3    154    2020-4-0
4    179    2020-5-0

In [74]:
# Remove rows with totals for country, provinces, ignored cases, and foriegners
no_total = ~cases['week_canton'].str.endswith("-0")
cases = cases[no_total]
no_total = ~cases['week_canton'].str.endswith("-1")
cases = cases[no_total]
no_total = ~cases['week_canton'].str.endswith("-2")
cases = cases[no_total]
no_total = ~cases['week_canton'].str.endswith("-3")
cases = cases[no_total]
no_total = ~cases['week_canton'].str.endswith("-4")
cases = cases[no_total]
no_total = ~cases['week_canton'].str.endswith("-5")
cases = cases[no_total]
no_total = ~cases['week_canton'].str.endswith("-6")
cases = cases[no_total]
no_total = ~cases['week_canton'].str.endswith("-7")
cases = cases[no_total]
no_total = ~cases['week_canton'].str.endswith("-99")
cases = cases[no_total]
no_total = ~cases['week_canton'].str.endswith("-98")
cases = cases[no_total]

In [75]:
no_total = ~cases['week_canton'].str.startswith("2020-53")
cases = cases[no_total]
no_total = ~cases['week_canton'].str.startswith("2021-53")
cases = cases[no_total]
no_total = ~cases['week_canton'].str.startswith("2022-53")
cases = cases[no_total]
no_total = ~cases['week_canton'].str.startswith("2023-53")
cases = cases[no_total]
no_total = ~cases['week_canton'].str.startswith("2024-53")
cases = cases[no_total]
no_total = ~cases['week_canton'].str.startswith("2025-53")
cases = cases[no_total]

In [76]:
cases.isna().sum()

casos          0
week_canton    0
dtype: int64

In [77]:
rr.head()

         rr week_canton clasi_rr clasi_rr_no_0
0  0.258311  2020-1-101    Medio          Bajo
1  0.930583  2020-2-101     Alto         Medio
2  1.356304  2020-3-101     Alto         Medio
3  0.657643  2020-4-101     Alto         Medio
4  0.000000  2020-5-101     Bajo          Bajo

In [78]:
rr.isna().sum()

rr               0
week_canton      0
clasi_rr         0
clasi_rr_no_0    0
dtype: int64

In [79]:
tmax.head()

   tmax_mean week_canton
0  33.578913  2020-1-507
1  33.366886  2020-2-507
2  33.510193  2020-3-507
3  33.203586  2020-4-507
4  33.583772  2020-5-507

In [80]:
tmax.isna().sum()

tmax_mean      0
week_canton    0
dtype: int64

In [81]:
tmin.head()

   tmin_mean week_canton
0  24.814801  2020-1-507
1  25.734802  2020-2-507
2  26.134207  2020-3-507
3  24.225476  2020-4-507
4  24.872407  2020-5-507

In [82]:
tmin.isna().sum()

tmin_mean      0
week_canton    0
dtype: int64

In [83]:
temp_prom.isna().sum()

temp_prom      0
week_canton    0
dtype: int64

In [84]:
precip.head()

,precip_total,precip_max,precip_min,precip_mean,precip_median,week_canton
0,3.039511,3.039511,0.0,0.607902,0.0,2020-1-507
1,0.000000,0.000000,0.0,0.000000,0.0,2020-2-507
2,0.000000,0.000000,0.0,0.000000,0.0,2020-3-507
3,0.899132,0.599422,0.0,0.128447,0.0,2020-4-507
4,1.259273,1.259273,0.0,0.179896,0.0,2020-5-507

In [85]:
precip.isna().sum()

precip_total     0
precip_max       0
precip_min       0
precip_mean      0
precip_median    0
week_canton      0
dtype: int64

In [86]:
ndvi.head()

  week_canton    ndvi
0  2020-1-201  0.8913
1  2020-1-205  0.7437
2  2020-1-203  0.7113
3  2020-1-215  0.7439
4  2020-1-214  0.7885

In [87]:
ndvi.isna().sum()

week_canton    0
ndvi           0
dtype: int64

In [88]:
sst.head()

  week_canton  nino34ssta
0  2020-1-101    0.535371
1  2020-1-102    0.535371
2  2020-1-103    0.535371
3  2020-1-104    0.535371
4  2020-1-105    0.535371

In [89]:
sst.isna().sum()

week_canton    0
nino34ssta     0
dtype: int64

In [90]:
urb.head()

   urb week_canton
0    1  2020-1-101
1    1  2020-1-102
2    1  2020-1-103
3    2  2020-1-104
4    2  2020-1-105

In [91]:
urb.isna().sum()

urb            0
week_canton    0
dtype: int64

In [92]:
# Remove week #53 to standardize with other datasets that only have 52 weeks
no_total = ~urb['week_canton'].str.contains("-53")
urb = urb[no_total]
no_total = ~urb['week_canton'].str.contains("-53")
urb = urb[no_total]
no_total = ~urb['week_canton'].str.contains("-53")
urb = urb[no_total]
no_total = ~urb['week_canton'].str.contains("-53")
urb = urb[no_total]
no_total = ~urb['week_canton'].str.contains("-53")
urb = urb[no_total]
no_total = ~urb['week_canton'].str.contains("-53")
urb = urb[no_total]
no_total = ~urb['week_canton'].str.contains("-53")
urb = urb[no_total]
no_total = ~urb['week_canton'].str.contains("-53")
urb = urb[no_total]
no_total = ~urb['week_canton'].str.contains("-53")
urb = urb[no_total]
no_total = ~urb['week_canton'].str.contains("-53")
urb = urb[no_total]

In [93]:
urb.shape

(25584, 2)

In [94]:
keywords.head()

,week_canton,aedes_aegypti,criaderos_de_mosquito,dengue,fiebre,plaquetas,buscar_trabajo,desempleo,empleo,comprar_carro,préstamo,tiquetes_avion,vacaciones,corte_agua,corte_de_agua,suspension_de_agua
0,2020-1-201,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2020-1-202,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2020-1-203,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2020-1-204,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2020-1-205,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [95]:
keywords.isna().sum()

week_canton              0
aedes_aegypti            0
criaderos_de_mosquito    0
dengue                   0
fiebre                   0
plaquetas                0
buscar_trabajo           0
desempleo                0
empleo                   0
comprar_carro            0
préstamo                 0
tiquetes_avion           0
vacaciones               0
corte_agua               0
corte_de_agua            0
suspension_de_agua       0
dtype: int64

In [96]:
# Dimensions

print(f"""
      cases: {cases.shape}
      rr: {rr.shape}
      ndvi: {ndvi.shape}
      tmax: {tmax.shape}
      tmin: {tmin.shape}
      sst: {sst.shape}
      precip: {precip.shape}
      urb: {urb.shape}
      keywords: {keywords.shape}
      """)

      cases: (25584, 2)
      rr: (25584, 4)
      ndvi: (25584, 2)
      tmax: (25584, 2)
      tmin: (25584, 2)
      sst: (25584, 2)
      precip: (25584, 6)
      urb: (25584, 2)
      keywords: (25584, 16)

# <a id='toc2_'></a>[Lags](#toc0_)

In [97]:
cases_lags.isna().sum()

week_canton    0
casos_lag_8    0
casos_lag_7    0
casos_lag_6    0
casos_lag_5    0
casos_lag_4    0
casos_lag_3    0
casos_lag_2    0
casos_lag_1    0
dtype: int64

In [98]:
rr_lags.isna().sum()

week_canton            0
rr_lag_8               0
rr_lag_7               0
rr_lag_6               0
rr_lag_5               0
rr_lag_4               0
rr_lag_3               0
rr_lag_2               0
rr_lag_1               0
clasi_rr_lag_8         0
clasi_rr_lag_7         0
clasi_rr_lag_6         0
clasi_rr_lag_5         0
clasi_rr_lag_4         0
clasi_rr_lag_3         0
clasi_rr_lag_2         0
clasi_rr_lag_1         0
clasi_rr_no_0_lag_8    0
clasi_rr_no_0_lag_7    0
clasi_rr_no_0_lag_6    0
clasi_rr_no_0_lag_5    0
clasi_rr_no_0_lag_4    0
clasi_rr_no_0_lag_3    0
clasi_rr_no_0_lag_2    0
clasi_rr_no_0_lag_1    0
dtype: int64

In [99]:
ndvi_lags.isna().sum()

week_canton    0
ndvi_lag_8     0
ndvi_lag_7     0
ndvi_lag_6     0
ndvi_lag_5     0
ndvi_lag_4     0
ndvi_lag_3     0
ndvi_lag_2     0
ndvi_lag_1     0
dtype: int64

In [100]:
tmax_lags.isna().sum()

week_canton        0
tmax_mean_lag_8    0
tmax_mean_lag_7    0
tmax_mean_lag_6    0
tmax_mean_lag_5    0
tmax_mean_lag_4    0
tmax_mean_lag_3    0
tmax_mean_lag_2    0
tmax_mean_lag_1    0
dtype: int64

In [101]:
semanas_nan_tmax_lags = tmax_lags[tmax_lags.isna().any(axis=1)]["week_canton"]
semanas_nan_tmax_lags[~semanas_nan_tmax_lags.str.endswith("-607")]

Series([], Name: week_canton, dtype: str)

In [102]:
precip_lags.isna().sum()

week_canton            0
precip_total_lag_8     0
precip_total_lag_7     0
precip_total_lag_6     0
precip_total_lag_5     0
precip_total_lag_4     0
precip_total_lag_3     0
precip_total_lag_2     0
precip_total_lag_1     0
precip_max_lag_8       0
precip_max_lag_7       0
precip_max_lag_6       0
precip_max_lag_5       0
precip_max_lag_4       0
precip_max_lag_3       0
precip_max_lag_2       0
precip_max_lag_1       0
precip_mean_lag_8      0
precip_mean_lag_7      0
precip_mean_lag_6      0
precip_mean_lag_5      0
precip_mean_lag_4      0
precip_mean_lag_3      0
precip_mean_lag_2      0
precip_mean_lag_1      0
precip_median_lag_8    0
precip_median_lag_7    0
precip_median_lag_6    0
precip_median_lag_5    0
precip_median_lag_4    0
precip_median_lag_3    0
precip_median_lag_2    0
precip_median_lag_1    0
precip_min_lag_8       0
precip_min_lag_7       0
precip_min_lag_6       0
precip_min_lag_5       0
precip_min_lag_4       0
precip_min_lag_3       0
precip_min_lag_2       0
precip_min_lag_1       0
dtype: int64

In [103]:
tmin_lags.isna().sum()

week_canton        0
tmin_mean_lag_8    0
tmin_mean_lag_7    0
tmin_mean_lag_6    0
tmin_mean_lag_5    0
tmin_mean_lag_4    0
tmin_mean_lag_3    0
tmin_mean_lag_2    0
tmin_mean_lag_1    0
dtype: int64

In [104]:
temp_prom_lags.isna().sum()

week_canton        0
temp_prom_lag_8    0
temp_prom_lag_7    0
temp_prom_lag_6    0
temp_prom_lag_5    0
temp_prom_lag_4    0
temp_prom_lag_3    0
temp_prom_lag_2    0
temp_prom_lag_1    0
dtype: int64

In [105]:
sst_lags.isna().sum()

week_canton         0
nino34ssta_lag_8    0
nino34ssta_lag_7    0
nino34ssta_lag_6    0
nino34ssta_lag_5    0
nino34ssta_lag_4    0
nino34ssta_lag_3    0
nino34ssta_lag_2    0
nino34ssta_lag_1    0
dtype: int64

In [106]:
keywords_lags.isna().sum()

week_canton            0
aedes_aegypti_lag_8    0
aedes_aegypti_lag_7    0
aedes_aegypti_lag_6    0
aedes_aegypti_lag_5    0
                      ..
dengue_lag_5           0
dengue_lag_4           0
dengue_lag_3           0
dengue_lag_2           0
dengue_lag_1           0
Length: 121, dtype: int64

# <a id='toc3_'></a>[Join](#toc0_)

In [107]:
print(f'Temp max shape: {tmax.shape}, temp min shape: {tmin.shape}')

Temp max shape: (25584, 2), temp min shape: (25584, 2)

In [108]:
temp = pd.merge(tmin, tmax, on='week_canton', how='inner')
temp = pd.merge(temp, temp_prom, on='week_canton', how='inner')

In [109]:
temp.shape

(25584, 4)

In [110]:
temp.head()

   tmin_mean week_canton  tmax_mean  temp_prom
0  24.814801  2020-1-507  33.578913  29.196857
1  25.734802  2020-2-507  33.366886  29.550844
2  26.134207  2020-3-507  33.510193  29.822200
3  24.225476  2020-4-507  33.203586  28.714531
4  24.872407  2020-5-507  33.583772  29.228089

In [111]:
print(f'Temp shape: {temp.shape}, precip shape: {precip.shape}')

Temp shape: (25584, 4), precip shape: (25584, 6)

In [112]:
temp_precip = pd.merge(temp, precip, on='week_canton', how='inner')

In [113]:
temp_precip.shape

(25584, 9)

In [114]:
temp_precip.head()

,tmin_mean,week_canton,tmax_mean,temp_prom,precip_total,precip_max,precip_min,precip_mean,precip_median
0,24.814801,2020-1-507,33.578913,29.196857,3.039511,3.039511,0.0,0.607902,0.0
1,25.734802,2020-2-507,33.366886,29.550844,0.000000,0.000000,0.0,0.000000,0.0
2,26.134207,2020-3-507,33.510193,29.822200,0.000000,0.000000,0.0,0.000000,0.0
3,24.225476,2020-4-507,33.203586,28.714531,0.899132,0.599422,0.0,0.128447,0.0
4,24.872407,2020-5-507,33.583772,29.228089,1.259273,1.259273,0.0,0.179896,0.0

In [115]:
print(f'Cases shape: {cases.shape}, rr shape: {rr.shape}, urb shape: {urb.shape}')

Cases shape: (25584, 2), rr shape: (25584, 4), urb shape: (25584, 2)

In [116]:
rr = rr.rename({"week-canton": "week_canton"})

In [117]:
rr.columns

Index(['rr', 'week_canton', 'clasi_rr', 'clasi_rr_no_0'], dtype='str')

In [118]:
rr.head()

         rr week_canton clasi_rr clasi_rr_no_0
0  0.258311  2020-1-101    Medio          Bajo
1  0.930583  2020-2-101     Alto         Medio
2  1.356304  2020-3-101     Alto         Medio
3  0.657643  2020-4-101     Alto         Medio
4  0.000000  2020-5-101     Bajo          Bajo

In [119]:
cases_rr = pd.merge(cases, rr, on=['week_canton'], how='inner')

In [120]:
cases_rr.shape

(25584, 5)

In [121]:
urb.head()

   urb week_canton
0    1  2020-1-101
1    1  2020-1-102
2    1  2020-1-103
3    2  2020-1-104
4    2  2020-1-105

In [122]:
demo = pd.merge(cases_rr, urb, on='week_canton', how='inner')
demo = pd.merge(demo, keywords, on='week_canton', how='inner')

In [123]:
demo.shape

(25584, 21)

In [124]:
demo.head()

,casos,week_canton,rr,clasi_rr,clasi_rr_no_0,urb,aedes_aegypti,criaderos_de_mosquito,dengue,fiebre,...,buscar_trabajo,desempleo,empleo,comprar_carro,préstamo,tiquetes_avion,vacaciones,corte_agua,corte_de_agua,suspension_de_agua
0,3,2020-1-101,0.258311,Medio,Bajo,1,0.0,0.0,0.0,0.0,...,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,11,2020-2-101,0.930583,Alto,Medio,1,0.0,0.0,0.0,0.0,...,0.0,0.0,48.57,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,15,2020-3-101,1.356304,Alto,Medio,1,0.0,0.0,0.0,0.0,...,0.0,0.0,41.14,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,7,2020-4-101,0.657643,Alto,Medio,1,0.0,0.0,0.0,0.0,...,0.0,0.0,46.86,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0,2020-5-101,0.000000,Bajo,Bajo,1,0.0,0.0,0.0,0.0,...,0.0,0.0,45.14,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [125]:
print(f'Demo shape: {demo.shape}, temp_precip shape: {temp_precip.shape}, expected shape: {(temp_precip.shape[0], demo.shape[1] + temp_precip.shape[1] - 1)}')

Demo shape: (25584, 21), temp_precip shape: (25584, 9), expected shape: (25584, 29)

In [126]:
demo_temp_precip = pd.merge(demo, temp_precip, on='week_canton', how='inner')

In [127]:
demo_temp_precip.shape

(25584, 29)

In [128]:
sst_ndvi = pd.merge(sst, ndvi, on='week_canton', how='inner')

In [129]:
sst_ndvi.shape

(25584, 3)

In [130]:
df_no_lag = pd.merge(demo_temp_precip, sst_ndvi, on='week_canton', how='inner')

In [131]:
df_no_lag.shape

(25584, 31)

In [132]:
cases_lags.shape

(24928, 9)

In [133]:
df_lag1 = pd.merge(df_no_lag, cases_lags, on='week_canton', how='inner')

In [134]:
df_lag1.shape

(24928, 39)

In [135]:
df_lag2 = pd.merge(df_lag1, rr_lags, on='week_canton', how='inner')
df_lag3 = pd.merge(df_lag2, ndvi_lags, on='week_canton', how='inner')
df_lag4 = pd.merge(df_lag3, tmax_lags, on='week_canton', how='inner')
df_lag5 = pd.merge(df_lag4, tmin_lags, on='week_canton', how='inner')
df_lag6 = pd.merge(df_lag5, sst_lags, on='week_canton', how='inner')
df_lag7 = pd.merge(df_lag6, temp_prom_lags, on='week_canton', how='inner')
df_lag8 = pd.merge(df_lag7, keywords_lags, on='week_canton', how='inner')
df = pd.merge(df_lag8, precip_lags, on='week_canton', how='inner')

In [136]:
df.shape

(24928, 263)

In [137]:
df.head()

,casos,week_canton,rr,clasi_rr,clasi_rr_no_0,urb,aedes_aegypti,criaderos_de_mosquito,dengue,fiebre,...,precip_median_lag_2,precip_median_lag_1,precip_min_lag_8,precip_min_lag_7,precip_min_lag_6,precip_min_lag_5,precip_min_lag_4,precip_min_lag_3,precip_min_lag_2,precip_min_lag_1
0,4,2020-9-101,0.459451,Medio,Bajo,1,0.0,0.0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2,2020-10-101,0.224397,Medio,Bajo,1,0.0,0.0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2,2020-11-101,0.253939,Medio,Bajo,1,0.0,0.0,0.0,11.34,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0,2020-12-101,0.000000,Bajo,Bajo,1,0.0,0.0,0.0,10.60,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0,2020-13-101,0.000000,Bajo,Bajo,1,0.0,0.0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [138]:
df.dtypes

casos                 int64
week_canton             str
rr                  float64
clasi_rr                str
clasi_rr_no_0           str
                     ...
precip_min_lag_5    float64
precip_min_lag_4    float64
precip_min_lag_3    float64
precip_min_lag_2    float64
precip_min_lag_1    float64
Length: 263, dtype: object

In [139]:
df['urb'] = df['urb'].astype('category')
df['clasi_rr'] = df['clasi_rr'].astype('category')
df['clasi_rr_lag_1'] = df['clasi_rr_lag_1'].astype('category')
df['clasi_rr_lag_2'] = df['clasi_rr_lag_2'].astype('category')
df['clasi_rr_lag_3'] = df['clasi_rr_lag_3'].astype('category')
df['clasi_rr_lag_4'] = df['clasi_rr_lag_4'].astype('category')
df['clasi_rr_lag_5'] = df['clasi_rr_lag_5'].astype('category')
df['clasi_rr_lag_6'] = df['clasi_rr_lag_6'].astype('category')
df['clasi_rr_lag_7'] = df['clasi_rr_lag_7'].astype('category')
df['clasi_rr_lag_8'] = df['clasi_rr_lag_8'].astype('category')

In [140]:
df.dtypes

casos                  int64
week_canton              str
rr                   float64
clasi_rr            category
clasi_rr_no_0            str
                      ...
precip_min_lag_5     float64
precip_min_lag_4     float64
precip_min_lag_3     float64
precip_min_lag_2     float64
precip_min_lag_1     float64
Length: 263, dtype: object

In [141]:
df.shape

(24928, 263)

In [143]:
df.to_csv('../data/clean/full_data.csv', index=False)